//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SqlServer.CatalogStore
{
    using System;
    using System.Data.SqlClient;
    using Microsoft.Data.Sqlite;
    using Microsoft.EntityFrameworkCore;
    
    
    [System.ComponentModel.DataAnnotations.Schema.TableAttribute("sys_assembly_files")]
    public partial class SysAssemblyFileCatalog
    {
        
        private System.Nullable<int> _assembly_id;
        
        private string _name;
        
        private System.Nullable<int> _file_id;
        
        private byte[] _content;
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("assembly_id")]
        public System.Nullable<int> AssemblyId
        {
            get
            {
                return this._assembly_id;
            }
            set
            {
                this._assembly_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("name")]
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("file_id")]
        public System.Nullable<int> FileId
        {
            get
            {
                return this._file_id;
            }
            set
            {
                this._file_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("content")]
        public byte[] Content
        {
            get
            {
                return this._content;
            }
            set
            {
                this._content = value;
            }
        }
    }
}
