//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SqlServer.CatalogStore
{
    using System;
    using System.Data.SqlClient;
    using Microsoft.Data.Sqlite;
    using Microsoft.EntityFrameworkCore;
    
    
    [System.ComponentModel.DataAnnotations.Schema.TableAttribute("sys_asymmetric_keys")]
    public partial class SysAsymmetricKeyCatalog
    {
        
        private string _name;
        
        private System.Nullable<int> _principal_id;
        
        private System.Nullable<int> _asymmetric_key_id;
        
        private string _pvt_key_encryption_type;
        
        private string _pvt_key_encryption_type_desc;
        
        private byte[] _thumbprint;
        
        private string _algorithm;
        
        private string _algorithm_desc;
        
        private System.Nullable<int> _key_length;
        
        private byte[] _sid;
        
        private string _string_sid;
        
        private byte[] _public_key;
        
        private string _attested_by;
        
        private string _provider_type;
        
        private System.Nullable<System.Guid> _cryptographic_provider_guid;
        
        private object _cryptographic_provider_algid;
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("name")]
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("principal_id")]
        public System.Nullable<int> PrincipalId
        {
            get
            {
                return this._principal_id;
            }
            set
            {
                this._principal_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("asymmetric_key_id")]
        public System.Nullable<int> AsymmetricKeyId
        {
            get
            {
                return this._asymmetric_key_id;
            }
            set
            {
                this._asymmetric_key_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("pvt_key_encryption_type")]
        public string PvtKeyEncryptionType
        {
            get
            {
                return this._pvt_key_encryption_type;
            }
            set
            {
                this._pvt_key_encryption_type = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("pvt_key_encryption_type_desc")]
        public string PvtKeyEncryptionTypeDesc
        {
            get
            {
                return this._pvt_key_encryption_type_desc;
            }
            set
            {
                this._pvt_key_encryption_type_desc = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("thumbprint")]
        public byte[] Thumbprint
        {
            get
            {
                return this._thumbprint;
            }
            set
            {
                this._thumbprint = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("algorithm")]
        public string Algorithm
        {
            get
            {
                return this._algorithm;
            }
            set
            {
                this._algorithm = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("algorithm_desc")]
        public string AlgorithmDesc
        {
            get
            {
                return this._algorithm_desc;
            }
            set
            {
                this._algorithm_desc = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("key_length")]
        public System.Nullable<int> KeyLength
        {
            get
            {
                return this._key_length;
            }
            set
            {
                this._key_length = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("sid")]
        public byte[] Sid
        {
            get
            {
                return this._sid;
            }
            set
            {
                this._sid = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("string_sid")]
        public string StringSid
        {
            get
            {
                return this._string_sid;
            }
            set
            {
                this._string_sid = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("public_key")]
        public byte[] PublicKey
        {
            get
            {
                return this._public_key;
            }
            set
            {
                this._public_key = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("attested_by")]
        public string AttestedBy
        {
            get
            {
                return this._attested_by;
            }
            set
            {
                this._attested_by = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("provider_type")]
        public string ProviderType
        {
            get
            {
                return this._provider_type;
            }
            set
            {
                this._provider_type = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("cryptographic_provider_guid")]
        public System.Nullable<System.Guid> CryptographicProviderGuid
        {
            get
            {
                return this._cryptographic_provider_guid;
            }
            set
            {
                this._cryptographic_provider_guid = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.NotMappedAttribute()]
        public object CryptographicProviderAlgid
        {
            get
            {
                return this._cryptographic_provider_algid;
            }
            set
            {
                this._cryptographic_provider_algid = value;
            }
        }
    }
}
