//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SqlServer.CatalogStore
{
    using System;
    using System.Data.SqlClient;
    using Microsoft.Data.Sqlite;
    using Microsoft.EntityFrameworkCore;
    
    
    [System.ComponentModel.DataAnnotations.Schema.TableAttribute("sys_assemblies")]
    public partial class SysAssemblyCatalog
    {
        
        private string _name;
        
        private System.Nullable<int> _principal_id;
        
        private System.Nullable<int> _assembly_id;
        
        private string _clr_name;
        
        private System.Nullable<byte> _permission_set;
        
        private string _permission_set_desc;
        
        private System.Nullable<bool> _is_visible;
        
        private System.Nullable<System.DateTime> _create_date;
        
        private System.Nullable<System.DateTime> _modify_date;
        
        private System.Nullable<bool> _is_user_defined;
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("name")]
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("principal_id")]
        public System.Nullable<int> PrincipalId
        {
            get
            {
                return this._principal_id;
            }
            set
            {
                this._principal_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("assembly_id")]
        public System.Nullable<int> AssemblyId
        {
            get
            {
                return this._assembly_id;
            }
            set
            {
                this._assembly_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("clr_name")]
        public string ClrName
        {
            get
            {
                return this._clr_name;
            }
            set
            {
                this._clr_name = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("permission_set")]
        public System.Nullable<byte> PermissionSet
        {
            get
            {
                return this._permission_set;
            }
            set
            {
                this._permission_set = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("permission_set_desc")]
        public string PermissionSetDesc
        {
            get
            {
                return this._permission_set_desc;
            }
            set
            {
                this._permission_set_desc = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("is_visible")]
        public System.Nullable<bool> IsVisible
        {
            get
            {
                return this._is_visible;
            }
            set
            {
                this._is_visible = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("create_date")]
        public System.Nullable<System.DateTime> CreateDate
        {
            get
            {
                return this._create_date;
            }
            set
            {
                this._create_date = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("modify_date")]
        public System.Nullable<System.DateTime> ModifyDate
        {
            get
            {
                return this._modify_date;
            }
            set
            {
                this._modify_date = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("is_user_defined")]
        public System.Nullable<bool> IsUserDefined
        {
            get
            {
                return this._is_user_defined;
            }
            set
            {
                this._is_user_defined = value;
            }
        }
    }
}
