//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SqlServer.CatalogStore
{
    using System;
    using System.Data.SqlClient;
    using Microsoft.Data.Sqlite;
    using Microsoft.EntityFrameworkCore;
    
    
    [System.ComponentModel.DataAnnotations.Schema.TableAttribute("sys_assembly_types")]
    public partial class SysAssemblyTypeCatalog
    {
        
        private string _name;
        
        private System.Nullable<byte> _system_type_id;
        
        private System.Nullable<int> _user_type_id;
        
        private System.Nullable<int> _schema_id;
        
        private System.Nullable<int> _principal_id;
        
        private System.Nullable<short> _max_length;
        
        private System.Nullable<byte> _precision;
        
        private System.Nullable<byte> _scale;
        
        private string _collation_name;
        
        private System.Nullable<bool> _is_nullable;
        
        private System.Nullable<bool> _is_user_defined;
        
        private System.Nullable<bool> _is_assembly_type;
        
        private System.Nullable<int> _default_object_id;
        
        private System.Nullable<int> _rule_object_id;
        
        private System.Nullable<int> _assembly_id;
        
        private string _assembly_class;
        
        private System.Nullable<bool> _is_binary_ordered;
        
        private System.Nullable<bool> _is_fixed_length;
        
        private string _prog_id;
        
        private string _assembly_qualified_name;
        
        private System.Nullable<bool> _is_table_type;
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("name")]
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("system_type_id")]
        public System.Nullable<byte> SystemTypeId
        {
            get
            {
                return this._system_type_id;
            }
            set
            {
                this._system_type_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("user_type_id")]
        public System.Nullable<int> UserTypeId
        {
            get
            {
                return this._user_type_id;
            }
            set
            {
                this._user_type_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("schema_id")]
        public System.Nullable<int> SchemaId
        {
            get
            {
                return this._schema_id;
            }
            set
            {
                this._schema_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("principal_id")]
        public System.Nullable<int> PrincipalId
        {
            get
            {
                return this._principal_id;
            }
            set
            {
                this._principal_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("max_length")]
        public System.Nullable<short> MaxLength
        {
            get
            {
                return this._max_length;
            }
            set
            {
                this._max_length = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("precision")]
        public System.Nullable<byte> Precision
        {
            get
            {
                return this._precision;
            }
            set
            {
                this._precision = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("scale")]
        public System.Nullable<byte> Scale
        {
            get
            {
                return this._scale;
            }
            set
            {
                this._scale = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("collation_name")]
        public string CollationName
        {
            get
            {
                return this._collation_name;
            }
            set
            {
                this._collation_name = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("is_nullable")]
        public System.Nullable<bool> IsNullable
        {
            get
            {
                return this._is_nullable;
            }
            set
            {
                this._is_nullable = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("is_user_defined")]
        public System.Nullable<bool> IsUserDefined
        {
            get
            {
                return this._is_user_defined;
            }
            set
            {
                this._is_user_defined = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("is_assembly_type")]
        public System.Nullable<bool> IsAssemblyType
        {
            get
            {
                return this._is_assembly_type;
            }
            set
            {
                this._is_assembly_type = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("default_object_id")]
        public System.Nullable<int> DefaultObjectId
        {
            get
            {
                return this._default_object_id;
            }
            set
            {
                this._default_object_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("rule_object_id")]
        public System.Nullable<int> RuleObjectId
        {
            get
            {
                return this._rule_object_id;
            }
            set
            {
                this._rule_object_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("assembly_id")]
        public System.Nullable<int> AssemblyId
        {
            get
            {
                return this._assembly_id;
            }
            set
            {
                this._assembly_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("assembly_class")]
        public string AssemblyClass
        {
            get
            {
                return this._assembly_class;
            }
            set
            {
                this._assembly_class = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("is_binary_ordered")]
        public System.Nullable<bool> IsBinaryOrdered
        {
            get
            {
                return this._is_binary_ordered;
            }
            set
            {
                this._is_binary_ordered = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("is_fixed_length")]
        public System.Nullable<bool> IsFixedLength
        {
            get
            {
                return this._is_fixed_length;
            }
            set
            {
                this._is_fixed_length = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("prog_id")]
        public string ProgId
        {
            get
            {
                return this._prog_id;
            }
            set
            {
                this._prog_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("assembly_qualified_name")]
        public string AssemblyQualifiedName
        {
            get
            {
                return this._assembly_qualified_name;
            }
            set
            {
                this._assembly_qualified_name = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("is_table_type")]
        public System.Nullable<bool> IsTableType
        {
            get
            {
                return this._is_table_type;
            }
            set
            {
                this._is_table_type = value;
            }
        }
    }
}
