//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SqlServer.CatalogStore
{
    using System;
    using System.Data.SqlClient;
    using Microsoft.Data.Sqlite;
    using Microsoft.EntityFrameworkCore;
    
    
    [System.ComponentModel.DataAnnotations.Schema.TableAttribute("sys_certificates")]
    public partial class SysCertificateCatalog
    {
        
        private string _name;
        
        private System.Nullable<int> _certificate_id;
        
        private System.Nullable<int> _principal_id;
        
        private string _pvt_key_encryption_type;
        
        private string _pvt_key_encryption_type_desc;
        
        private System.Nullable<bool> _is_active_for_begin_dialog;
        
        private string _issuer_name;
        
        private string _cert_serial_number;
        
        private byte[] _sid;
        
        private string _string_sid;
        
        private string _subject;
        
        private System.Nullable<System.DateTime> _expiry_date;
        
        private System.Nullable<System.DateTime> _start_date;
        
        private byte[] _thumbprint;
        
        private string _attested_by;
        
        private System.Nullable<System.DateTime> _pvt_key_last_backup_date;
        
        private System.Nullable<int> _key_length;
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("name")]
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("certificate_id")]
        public System.Nullable<int> CertificateId
        {
            get
            {
                return this._certificate_id;
            }
            set
            {
                this._certificate_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("principal_id")]
        public System.Nullable<int> PrincipalId
        {
            get
            {
                return this._principal_id;
            }
            set
            {
                this._principal_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("pvt_key_encryption_type")]
        public string PvtKeyEncryptionType
        {
            get
            {
                return this._pvt_key_encryption_type;
            }
            set
            {
                this._pvt_key_encryption_type = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("pvt_key_encryption_type_desc")]
        public string PvtKeyEncryptionTypeDesc
        {
            get
            {
                return this._pvt_key_encryption_type_desc;
            }
            set
            {
                this._pvt_key_encryption_type_desc = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("is_active_for_begin_dialog")]
        public System.Nullable<bool> IsActiveForBeginDialog
        {
            get
            {
                return this._is_active_for_begin_dialog;
            }
            set
            {
                this._is_active_for_begin_dialog = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("issuer_name")]
        public string IssuerName
        {
            get
            {
                return this._issuer_name;
            }
            set
            {
                this._issuer_name = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("cert_serial_number")]
        public string CertSerialNumber
        {
            get
            {
                return this._cert_serial_number;
            }
            set
            {
                this._cert_serial_number = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("sid")]
        public byte[] Sid
        {
            get
            {
                return this._sid;
            }
            set
            {
                this._sid = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("string_sid")]
        public string StringSid
        {
            get
            {
                return this._string_sid;
            }
            set
            {
                this._string_sid = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("subject")]
        public string Subject
        {
            get
            {
                return this._subject;
            }
            set
            {
                this._subject = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("expiry_date")]
        public System.Nullable<System.DateTime> ExpiryDate
        {
            get
            {
                return this._expiry_date;
            }
            set
            {
                this._expiry_date = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("start_date")]
        public System.Nullable<System.DateTime> StartDate
        {
            get
            {
                return this._start_date;
            }
            set
            {
                this._start_date = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("thumbprint")]
        public byte[] Thumbprint
        {
            get
            {
                return this._thumbprint;
            }
            set
            {
                this._thumbprint = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("attested_by")]
        public string AttestedBy
        {
            get
            {
                return this._attested_by;
            }
            set
            {
                this._attested_by = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("pvt_key_last_backup_date")]
        public System.Nullable<System.DateTime> PvtKeyLastBackupDate
        {
            get
            {
                return this._pvt_key_last_backup_date;
            }
            set
            {
                this._pvt_key_last_backup_date = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("key_length")]
        public System.Nullable<int> KeyLength
        {
            get
            {
                return this._key_length;
            }
            set
            {
                this._key_length = value;
            }
        }
    }
}
