//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SqlServer.CatalogStore
{
    using System;
    using System.Data.SqlClient;
    using Microsoft.Data.Sqlite;
    using Microsoft.EntityFrameworkCore;
    
    
    [System.ComponentModel.DataAnnotations.Schema.TableAttribute("sys_cryptographic_providers")]
    public partial class SysCryptographicProviderCatalog
    {
        
        private System.Nullable<int> _provider_id;
        
        private string _name;
        
        private System.Nullable<System.Guid> _guid;
        
        private string _version;
        
        private string _dll_path;
        
        private System.Nullable<bool> _is_enabled;
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("provider_id")]
        public System.Nullable<int> ProviderId
        {
            get
            {
                return this._provider_id;
            }
            set
            {
                this._provider_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("name")]
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("guid")]
        public System.Nullable<System.Guid> Guid
        {
            get
            {
                return this._guid;
            }
            set
            {
                this._guid = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("version")]
        public string Version
        {
            get
            {
                return this._version;
            }
            set
            {
                this._version = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("dll_path")]
        public string DllPath
        {
            get
            {
                return this._dll_path;
            }
            set
            {
                this._dll_path = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("is_enabled")]
        public System.Nullable<bool> IsEnabled
        {
            get
            {
                return this._is_enabled;
            }
            set
            {
                this._is_enabled = value;
            }
        }
    }
}
