//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SqlServer.CatalogStore
{
    using System;
    using System.Data.SqlClient;
    using Microsoft.Data.Sqlite;
    using Microsoft.EntityFrameworkCore;
    
    
    [System.ComponentModel.DataAnnotations.Schema.TableAttribute("sys_conversation_priorities")]
    public partial class SysConversationPriorityCatalog
    {
        
        private System.Nullable<int> _priority_id;
        
        private string _name;
        
        private System.Nullable<int> _service_contract_id;
        
        private System.Nullable<int> _local_service_id;
        
        private string _remote_service_name;
        
        private System.Nullable<byte> _priority;
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("priority_id")]
        public System.Nullable<int> PriorityId
        {
            get
            {
                return this._priority_id;
            }
            set
            {
                this._priority_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("name")]
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("service_contract_id")]
        public System.Nullable<int> ServiceContractId
        {
            get
            {
                return this._service_contract_id;
            }
            set
            {
                this._service_contract_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("local_service_id")]
        public System.Nullable<int> LocalServiceId
        {
            get
            {
                return this._local_service_id;
            }
            set
            {
                this._local_service_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("remote_service_name")]
        public string RemoteServiceName
        {
            get
            {
                return this._remote_service_name;
            }
            set
            {
                this._remote_service_name = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("priority")]
        public System.Nullable<byte> Priority
        {
            get
            {
                return this._priority;
            }
            set
            {
                this._priority = value;
            }
        }
    }
}
