//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SqlServer.CatalogStore
{
    using System;
    using System.Data.SqlClient;
    using Microsoft.Data.Sqlite;
    using Microsoft.EntityFrameworkCore;
    
    
    [System.ComponentModel.DataAnnotations.Schema.TableAttribute("sys_change_tracking_tables")]
    public partial class SysChangeTrackingTableCatalog
    {
        
        private System.Nullable<int> _object_id;
        
        private System.Nullable<bool> _is_track_columns_updated_on;
        
        private System.Nullable<long> _min_valid_version;
        
        private System.Nullable<long> _begin_version;
        
        private System.Nullable<long> _cleanup_version;
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("object_id")]
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public System.Nullable<int> ObjectId
        {
            get
            {
                return this._object_id;
            }
            set
            {
                this._object_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("is_track_columns_updated_on")]
        public System.Nullable<bool> IsTrackColumnsUpdatedOn
        {
            get
            {
                return this._is_track_columns_updated_on;
            }
            set
            {
                this._is_track_columns_updated_on = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("min_valid_version")]
        public System.Nullable<long> MinValidVersion
        {
            get
            {
                return this._min_valid_version;
            }
            set
            {
                this._min_valid_version = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("begin_version")]
        public System.Nullable<long> BeginVersion
        {
            get
            {
                return this._begin_version;
            }
            set
            {
                this._begin_version = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("cleanup_version")]
        public System.Nullable<long> CleanupVersion
        {
            get
            {
                return this._cleanup_version;
            }
            set
            {
                this._cleanup_version = value;
            }
        }
    }
}
