//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SqlServer.CatalogStore
{
    using System;
    using System.Data.SqlClient;
    using Microsoft.Data.Sqlite;
    using Microsoft.EntityFrameworkCore;
    
    
    [System.ComponentModel.DataAnnotations.Schema.TableAttribute("sys_column_encryption_key_values")]
    public partial class SysColumnEncryptionKeyValueCatalog
    {
        
        private System.Nullable<int> _column_encryption_key_id;
        
        private System.Nullable<int> _column_master_key_id;
        
        private byte[] _encrypted_value;
        
        private string _encryption_algorithm_name;
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("column_encryption_key_id")]
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public System.Nullable<int> ColumnEncryptionKeyId
        {
            get
            {
                return this._column_encryption_key_id;
            }
            set
            {
                this._column_encryption_key_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("column_master_key_id")]
        public System.Nullable<int> ColumnMasterKeyId
        {
            get
            {
                return this._column_master_key_id;
            }
            set
            {
                this._column_master_key_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("encrypted_value")]
        public byte[] EncryptedValue
        {
            get
            {
                return this._encrypted_value;
            }
            set
            {
                this._encrypted_value = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("encryption_algorithm_name")]
        public string EncryptionAlgorithmName
        {
            get
            {
                return this._encryption_algorithm_name;
            }
            set
            {
                this._encryption_algorithm_name = value;
            }
        }
    }
}
