//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SqlServer.CatalogStore
{
    using System;
    using System.Data.SqlClient;
    using Microsoft.Data.Sqlite;
    using Microsoft.EntityFrameworkCore;
    
    
    [System.ComponentModel.DataAnnotations.Schema.TableAttribute("sys_database_filestream_options")]
    public partial class SysDatabaseFilestreamOptionCatalog
    {
        
        private System.Nullable<int> _database_id;
        
        private System.Nullable<byte> _non_transacted_access;
        
        private string _non_transacted_access_desc;
        
        private string _directory_name;
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("database_id")]
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public System.Nullable<int> DatabaseId
        {
            get
            {
                return this._database_id;
            }
            set
            {
                this._database_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("non_transacted_access")]
        public System.Nullable<byte> NonTransactedAccess
        {
            get
            {
                return this._non_transacted_access;
            }
            set
            {
                this._non_transacted_access = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("non_transacted_access_desc")]
        public string NonTransactedAccessDesc
        {
            get
            {
                return this._non_transacted_access_desc;
            }
            set
            {
                this._non_transacted_access_desc = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("directory_name")]
        public string DirectoryName
        {
            get
            {
                return this._directory_name;
            }
            set
            {
                this._directory_name = value;
            }
        }
    }
}
