//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SqlServer.CatalogStore
{
    using System;
    using System.Data.SqlClient;
    using Microsoft.Data.Sqlite;
    using Microsoft.EntityFrameworkCore;
    
    
    [System.ComponentModel.DataAnnotations.Schema.TableAttribute("sys_database_permissions")]
    public partial class SysDatabasePermissionCatalog
    {
        
        private System.Nullable<byte> _class;
        
        private string _class_desc;
        
        private System.Nullable<int> _major_id;
        
        private System.Nullable<int> _minor_id;
        
        private System.Nullable<int> _grantee_principal_id;
        
        private System.Nullable<int> _grantor_principal_id;
        
        private string _type;
        
        private string _permission_name;
        
        private string _state;
        
        private string _state_desc;
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("class")]
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public System.Nullable<byte> Class
        {
            get
            {
                return this._class;
            }
            set
            {
                this._class = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("class_desc")]
        public string ClassDesc
        {
            get
            {
                return this._class_desc;
            }
            set
            {
                this._class_desc = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("major_id")]
        public System.Nullable<int> MajorId
        {
            get
            {
                return this._major_id;
            }
            set
            {
                this._major_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("minor_id")]
        public System.Nullable<int> MinorId
        {
            get
            {
                return this._minor_id;
            }
            set
            {
                this._minor_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("grantee_principal_id")]
        public System.Nullable<int> GranteePrincipalId
        {
            get
            {
                return this._grantee_principal_id;
            }
            set
            {
                this._grantee_principal_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("grantor_principal_id")]
        public System.Nullable<int> GrantorPrincipalId
        {
            get
            {
                return this._grantor_principal_id;
            }
            set
            {
                this._grantor_principal_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("type")]
        public string Type
        {
            get
            {
                return this._type;
            }
            set
            {
                this._type = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("permission_name")]
        public string PermissionName
        {
            get
            {
                return this._permission_name;
            }
            set
            {
                this._permission_name = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("state")]
        public string State
        {
            get
            {
                return this._state;
            }
            set
            {
                this._state = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("state_desc")]
        public string StateDesc
        {
            get
            {
                return this._state_desc;
            }
            set
            {
                this._state_desc = value;
            }
        }
    }
}
