//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SqlServer.CatalogStore
{
    using System;
    using System.Data.SqlClient;
    using Microsoft.Data.Sqlite;
    using Microsoft.EntityFrameworkCore;
    
    
    [System.ComponentModel.DataAnnotations.Schema.TableAttribute("sys_database_audit_specification_details")]
    public partial class SysDatabaseAuditSpecificationDetailCatalog
    {
        
        private System.Nullable<int> _database_specification_id;
        
        private string _audit_action_id;
        
        private string _audit_action_name;
        
        private System.Nullable<byte> _class;
        
        private string _class_desc;
        
        private System.Nullable<int> _major_id;
        
        private System.Nullable<int> _minor_id;
        
        private System.Nullable<int> _audited_principal_id;
        
        private string _audited_result;
        
        private System.Nullable<bool> _is_group;
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("database_specification_id")]
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public System.Nullable<int> DatabaseSpecificationId
        {
            get
            {
                return this._database_specification_id;
            }
            set
            {
                this._database_specification_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("audit_action_id")]
        public string AuditActionId
        {
            get
            {
                return this._audit_action_id;
            }
            set
            {
                this._audit_action_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("audit_action_name")]
        public string AuditActionName
        {
            get
            {
                return this._audit_action_name;
            }
            set
            {
                this._audit_action_name = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("class")]
        public System.Nullable<byte> Class
        {
            get
            {
                return this._class;
            }
            set
            {
                this._class = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("class_desc")]
        public string ClassDesc
        {
            get
            {
                return this._class_desc;
            }
            set
            {
                this._class_desc = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("major_id")]
        public System.Nullable<int> MajorId
        {
            get
            {
                return this._major_id;
            }
            set
            {
                this._major_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("minor_id")]
        public System.Nullable<int> MinorId
        {
            get
            {
                return this._minor_id;
            }
            set
            {
                this._minor_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("audited_principal_id")]
        public System.Nullable<int> AuditedPrincipalId
        {
            get
            {
                return this._audited_principal_id;
            }
            set
            {
                this._audited_principal_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("audited_result")]
        public string AuditedResult
        {
            get
            {
                return this._audited_result;
            }
            set
            {
                this._audited_result = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("is_group")]
        public System.Nullable<bool> IsGroup
        {
            get
            {
                return this._is_group;
            }
            set
            {
                this._is_group = value;
            }
        }
    }
}
