//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SqlServer.CatalogStore
{
    using System;
    using System.Data.SqlClient;
    using Microsoft.Data.Sqlite;
    using Microsoft.EntityFrameworkCore;
    
    
    [System.ComponentModel.DataAnnotations.Schema.TableAttribute("sys_database_mirroring")]
    public partial class SysDatabaseMirroringCatalog
    {
        
        private System.Nullable<int> _database_id;
        
        private System.Nullable<System.Guid> _mirroring_guid;
        
        private System.Nullable<byte> _mirroring_state;
        
        private string _mirroring_state_desc;
        
        private System.Nullable<byte> _mirroring_role;
        
        private string _mirroring_role_desc;
        
        private System.Nullable<int> _mirroring_role_sequence;
        
        private System.Nullable<byte> _mirroring_safety_level;
        
        private string _mirroring_safety_level_desc;
        
        private System.Nullable<int> _mirroring_safety_sequence;
        
        private string _mirroring_partner_name;
        
        private string _mirroring_partner_instance;
        
        private string _mirroring_witness_name;
        
        private System.Nullable<byte> _mirroring_witness_state;
        
        private string _mirroring_witness_state_desc;
        
        private System.Nullable<decimal> _mirroring_failover_lsn;
        
        private System.Nullable<int> _mirroring_connection_timeout;
        
        private System.Nullable<int> _mirroring_redo_queue;
        
        private string _mirroring_redo_queue_type;
        
        private System.Nullable<decimal> _mirroring_end_of_log_lsn;
        
        private System.Nullable<decimal> _mirroring_replication_lsn;
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("database_id")]
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public System.Nullable<int> DatabaseId
        {
            get
            {
                return this._database_id;
            }
            set
            {
                this._database_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("mirroring_guid")]
        public System.Nullable<System.Guid> MirroringGuid
        {
            get
            {
                return this._mirroring_guid;
            }
            set
            {
                this._mirroring_guid = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("mirroring_state")]
        public System.Nullable<byte> MirroringState
        {
            get
            {
                return this._mirroring_state;
            }
            set
            {
                this._mirroring_state = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("mirroring_state_desc")]
        public string MirroringStateDesc
        {
            get
            {
                return this._mirroring_state_desc;
            }
            set
            {
                this._mirroring_state_desc = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("mirroring_role")]
        public System.Nullable<byte> MirroringRole
        {
            get
            {
                return this._mirroring_role;
            }
            set
            {
                this._mirroring_role = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("mirroring_role_desc")]
        public string MirroringRoleDesc
        {
            get
            {
                return this._mirroring_role_desc;
            }
            set
            {
                this._mirroring_role_desc = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("mirroring_role_sequence")]
        public System.Nullable<int> MirroringRoleSequence
        {
            get
            {
                return this._mirroring_role_sequence;
            }
            set
            {
                this._mirroring_role_sequence = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("mirroring_safety_level")]
        public System.Nullable<byte> MirroringSafetyLevel
        {
            get
            {
                return this._mirroring_safety_level;
            }
            set
            {
                this._mirroring_safety_level = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("mirroring_safety_level_desc")]
        public string MirroringSafetyLevelDesc
        {
            get
            {
                return this._mirroring_safety_level_desc;
            }
            set
            {
                this._mirroring_safety_level_desc = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("mirroring_safety_sequence")]
        public System.Nullable<int> MirroringSafetySequence
        {
            get
            {
                return this._mirroring_safety_sequence;
            }
            set
            {
                this._mirroring_safety_sequence = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("mirroring_partner_name")]
        public string MirroringPartnerName
        {
            get
            {
                return this._mirroring_partner_name;
            }
            set
            {
                this._mirroring_partner_name = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("mirroring_partner_instance")]
        public string MirroringPartnerInstance
        {
            get
            {
                return this._mirroring_partner_instance;
            }
            set
            {
                this._mirroring_partner_instance = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("mirroring_witness_name")]
        public string MirroringWitnessName
        {
            get
            {
                return this._mirroring_witness_name;
            }
            set
            {
                this._mirroring_witness_name = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("mirroring_witness_state")]
        public System.Nullable<byte> MirroringWitnessState
        {
            get
            {
                return this._mirroring_witness_state;
            }
            set
            {
                this._mirroring_witness_state = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("mirroring_witness_state_desc")]
        public string MirroringWitnessStateDesc
        {
            get
            {
                return this._mirroring_witness_state_desc;
            }
            set
            {
                this._mirroring_witness_state_desc = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("mirroring_failover_lsn")]
        public System.Nullable<decimal> MirroringFailoverLsn
        {
            get
            {
                return this._mirroring_failover_lsn;
            }
            set
            {
                this._mirroring_failover_lsn = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("mirroring_connection_timeout")]
        public System.Nullable<int> MirroringConnectionTimeout
        {
            get
            {
                return this._mirroring_connection_timeout;
            }
            set
            {
                this._mirroring_connection_timeout = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("mirroring_redo_queue")]
        public System.Nullable<int> MirroringRedoQueue
        {
            get
            {
                return this._mirroring_redo_queue;
            }
            set
            {
                this._mirroring_redo_queue = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("mirroring_redo_queue_type")]
        public string MirroringRedoQueueType
        {
            get
            {
                return this._mirroring_redo_queue_type;
            }
            set
            {
                this._mirroring_redo_queue_type = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("mirroring_end_of_log_lsn")]
        public System.Nullable<decimal> MirroringEndOfLogLsn
        {
            get
            {
                return this._mirroring_end_of_log_lsn;
            }
            set
            {
                this._mirroring_end_of_log_lsn = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("mirroring_replication_lsn")]
        public System.Nullable<decimal> MirroringReplicationLsn
        {
            get
            {
                return this._mirroring_replication_lsn;
            }
            set
            {
                this._mirroring_replication_lsn = value;
            }
        }
    }
}
