//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SqlServer.CatalogStore
{
    using System;
    using System.Data.SqlClient;
    using Microsoft.Data.Sqlite;
    using Microsoft.EntityFrameworkCore;
    
    
    [System.ComponentModel.DataAnnotations.Schema.TableAttribute("sys_database_role_members")]
    public partial class SysDatabaseRoleMemberCatalog
    {
        
        private System.Nullable<int> _role_principal_id;
        
        private System.Nullable<int> _member_principal_id;
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("role_principal_id")]
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public System.Nullable<int> RolePrincipalId
        {
            get
            {
                return this._role_principal_id;
            }
            set
            {
                this._role_principal_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("member_principal_id")]
        public System.Nullable<int> MemberPrincipalId
        {
            get
            {
                return this._member_principal_id;
            }
            set
            {
                this._member_principal_id = value;
            }
        }
    }
}
