//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SqlServer.CatalogStore
{
    using System;
    using System.Data.SqlClient;
    using Microsoft.Data.Sqlite;
    using Microsoft.EntityFrameworkCore;
    
    
    [System.ComponentModel.DataAnnotations.Schema.TableAttribute("sys_database_mirroring_endpoints")]
    public partial class SysDatabaseMirroringEndpointCatalog
    {
        
        private string _name;
        
        private System.Nullable<int> _endpoint_id;
        
        private System.Nullable<int> _principal_id;
        
        private System.Nullable<byte> _protocol;
        
        private string _protocol_desc;
        
        private System.Nullable<byte> _type;
        
        private string _type_desc;
        
        private System.Nullable<byte> _state;
        
        private string _state_desc;
        
        private System.Nullable<bool> _is_admin_endpoint;
        
        private System.Nullable<byte> _role;
        
        private string _role_desc;
        
        private System.Nullable<bool> _is_encryption_enabled;
        
        private System.Nullable<byte> _connection_auth;
        
        private string _connection_auth_desc;
        
        private System.Nullable<int> _certificate_id;
        
        private System.Nullable<byte> _encryption_algorithm;
        
        private string _encryption_algorithm_desc;
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("name")]
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("endpoint_id")]
        public System.Nullable<int> EndpointId
        {
            get
            {
                return this._endpoint_id;
            }
            set
            {
                this._endpoint_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("principal_id")]
        public System.Nullable<int> PrincipalId
        {
            get
            {
                return this._principal_id;
            }
            set
            {
                this._principal_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("protocol")]
        public System.Nullable<byte> Protocol
        {
            get
            {
                return this._protocol;
            }
            set
            {
                this._protocol = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("protocol_desc")]
        public string ProtocolDesc
        {
            get
            {
                return this._protocol_desc;
            }
            set
            {
                this._protocol_desc = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("type")]
        public System.Nullable<byte> Type
        {
            get
            {
                return this._type;
            }
            set
            {
                this._type = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("type_desc")]
        public string TypeDesc
        {
            get
            {
                return this._type_desc;
            }
            set
            {
                this._type_desc = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("state")]
        public System.Nullable<byte> State
        {
            get
            {
                return this._state;
            }
            set
            {
                this._state = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("state_desc")]
        public string StateDesc
        {
            get
            {
                return this._state_desc;
            }
            set
            {
                this._state_desc = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("is_admin_endpoint")]
        public System.Nullable<bool> IsAdminEndpoint
        {
            get
            {
                return this._is_admin_endpoint;
            }
            set
            {
                this._is_admin_endpoint = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("role")]
        public System.Nullable<byte> Role
        {
            get
            {
                return this._role;
            }
            set
            {
                this._role = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("role_desc")]
        public string RoleDesc
        {
            get
            {
                return this._role_desc;
            }
            set
            {
                this._role_desc = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("is_encryption_enabled")]
        public System.Nullable<bool> IsEncryptionEnabled
        {
            get
            {
                return this._is_encryption_enabled;
            }
            set
            {
                this._is_encryption_enabled = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("connection_auth")]
        public System.Nullable<byte> ConnectionAuth
        {
            get
            {
                return this._connection_auth;
            }
            set
            {
                this._connection_auth = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("connection_auth_desc")]
        public string ConnectionAuthDesc
        {
            get
            {
                return this._connection_auth_desc;
            }
            set
            {
                this._connection_auth_desc = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("certificate_id")]
        public System.Nullable<int> CertificateId
        {
            get
            {
                return this._certificate_id;
            }
            set
            {
                this._certificate_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("encryption_algorithm")]
        public System.Nullable<byte> EncryptionAlgorithm
        {
            get
            {
                return this._encryption_algorithm;
            }
            set
            {
                this._encryption_algorithm = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("encryption_algorithm_desc")]
        public string EncryptionAlgorithmDesc
        {
            get
            {
                return this._encryption_algorithm_desc;
            }
            set
            {
                this._encryption_algorithm_desc = value;
            }
        }
    }
}
