//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SqlServer.CatalogStore
{
    using System;
    using System.Data.SqlClient;
    using Microsoft.Data.Sqlite;
    using Microsoft.EntityFrameworkCore;
    
    
    [System.ComponentModel.DataAnnotations.Schema.TableAttribute("sys_database_files")]
    public partial class SysDatabaseFileCatalog
    {
        
        private System.Nullable<int> _file_id;
        
        private System.Nullable<System.Guid> _file_guid;
        
        private System.Nullable<byte> _type;
        
        private string _type_desc;
        
        private System.Nullable<int> _data_space_id;
        
        private string _name;
        
        private string _physical_name;
        
        private System.Nullable<byte> _state;
        
        private string _state_desc;
        
        private System.Nullable<int> _size;
        
        private System.Nullable<int> _max_size;
        
        private System.Nullable<int> _growth;
        
        private System.Nullable<bool> _is_media_read_only;
        
        private System.Nullable<bool> _is_read_only;
        
        private System.Nullable<bool> _is_sparse;
        
        private System.Nullable<bool> _is_percent_growth;
        
        private System.Nullable<bool> _is_name_reserved;
        
        private System.Nullable<bool> _is_persistent_log_buffer;
        
        private System.Nullable<decimal> _create_lsn;
        
        private System.Nullable<decimal> _drop_lsn;
        
        private System.Nullable<decimal> _read_only_lsn;
        
        private System.Nullable<decimal> _read_write_lsn;
        
        private System.Nullable<decimal> _differential_base_lsn;
        
        private System.Nullable<System.Guid> _differential_base_guid;
        
        private System.Nullable<System.DateTime> _differential_base_time;
        
        private System.Nullable<decimal> _redo_start_lsn;
        
        private System.Nullable<System.Guid> _redo_start_fork_guid;
        
        private System.Nullable<decimal> _redo_target_lsn;
        
        private System.Nullable<System.Guid> _redo_target_fork_guid;
        
        private System.Nullable<decimal> _backup_lsn;
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("file_id")]
        public System.Nullable<int> FileId
        {
            get
            {
                return this._file_id;
            }
            set
            {
                this._file_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("file_guid")]
        public System.Nullable<System.Guid> FileGuid
        {
            get
            {
                return this._file_guid;
            }
            set
            {
                this._file_guid = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("type")]
        public System.Nullable<byte> Type
        {
            get
            {
                return this._type;
            }
            set
            {
                this._type = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("type_desc")]
        public string TypeDesc
        {
            get
            {
                return this._type_desc;
            }
            set
            {
                this._type_desc = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("data_space_id")]
        public System.Nullable<int> DataSpaceId
        {
            get
            {
                return this._data_space_id;
            }
            set
            {
                this._data_space_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("name")]
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("physical_name")]
        public string PhysicalName
        {
            get
            {
                return this._physical_name;
            }
            set
            {
                this._physical_name = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("state")]
        public System.Nullable<byte> State
        {
            get
            {
                return this._state;
            }
            set
            {
                this._state = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("state_desc")]
        public string StateDesc
        {
            get
            {
                return this._state_desc;
            }
            set
            {
                this._state_desc = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("size")]
        public System.Nullable<int> Size
        {
            get
            {
                return this._size;
            }
            set
            {
                this._size = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("max_size")]
        public System.Nullable<int> MaxSize
        {
            get
            {
                return this._max_size;
            }
            set
            {
                this._max_size = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("growth")]
        public System.Nullable<int> Growth
        {
            get
            {
                return this._growth;
            }
            set
            {
                this._growth = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("is_media_read_only")]
        public System.Nullable<bool> IsMediaReadOnly
        {
            get
            {
                return this._is_media_read_only;
            }
            set
            {
                this._is_media_read_only = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("is_read_only")]
        public System.Nullable<bool> IsReadOnly
        {
            get
            {
                return this._is_read_only;
            }
            set
            {
                this._is_read_only = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("is_sparse")]
        public System.Nullable<bool> IsSparse
        {
            get
            {
                return this._is_sparse;
            }
            set
            {
                this._is_sparse = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("is_percent_growth")]
        public System.Nullable<bool> IsPercentGrowth
        {
            get
            {
                return this._is_percent_growth;
            }
            set
            {
                this._is_percent_growth = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("is_name_reserved")]
        public System.Nullable<bool> IsNameReserved
        {
            get
            {
                return this._is_name_reserved;
            }
            set
            {
                this._is_name_reserved = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("is_persistent_log_buffer")]
        public System.Nullable<bool> IsPersistentLogBuffer
        {
            get
            {
                return this._is_persistent_log_buffer;
            }
            set
            {
                this._is_persistent_log_buffer = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("create_lsn")]
        public System.Nullable<decimal> CreateLsn
        {
            get
            {
                return this._create_lsn;
            }
            set
            {
                this._create_lsn = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("drop_lsn")]
        public System.Nullable<decimal> DropLsn
        {
            get
            {
                return this._drop_lsn;
            }
            set
            {
                this._drop_lsn = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("read_only_lsn")]
        public System.Nullable<decimal> ReadOnlyLsn
        {
            get
            {
                return this._read_only_lsn;
            }
            set
            {
                this._read_only_lsn = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("read_write_lsn")]
        public System.Nullable<decimal> ReadWriteLsn
        {
            get
            {
                return this._read_write_lsn;
            }
            set
            {
                this._read_write_lsn = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("differential_base_lsn")]
        public System.Nullable<decimal> DifferentialBaseLsn
        {
            get
            {
                return this._differential_base_lsn;
            }
            set
            {
                this._differential_base_lsn = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("differential_base_guid")]
        public System.Nullable<System.Guid> DifferentialBaseGuid
        {
            get
            {
                return this._differential_base_guid;
            }
            set
            {
                this._differential_base_guid = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("differential_base_time")]
        public System.Nullable<System.DateTime> DifferentialBaseTime
        {
            get
            {
                return this._differential_base_time;
            }
            set
            {
                this._differential_base_time = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("redo_start_lsn")]
        public System.Nullable<decimal> RedoStartLsn
        {
            get
            {
                return this._redo_start_lsn;
            }
            set
            {
                this._redo_start_lsn = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("redo_start_fork_guid")]
        public System.Nullable<System.Guid> RedoStartForkGuid
        {
            get
            {
                return this._redo_start_fork_guid;
            }
            set
            {
                this._redo_start_fork_guid = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("redo_target_lsn")]
        public System.Nullable<decimal> RedoTargetLsn
        {
            get
            {
                return this._redo_target_lsn;
            }
            set
            {
                this._redo_target_lsn = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("redo_target_fork_guid")]
        public System.Nullable<System.Guid> RedoTargetForkGuid
        {
            get
            {
                return this._redo_target_fork_guid;
            }
            set
            {
                this._redo_target_fork_guid = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("backup_lsn")]
        public System.Nullable<decimal> BackupLsn
        {
            get
            {
                return this._backup_lsn;
            }
            set
            {
                this._backup_lsn = value;
            }
        }
    }
}
