//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SqlServer.CatalogStore
{
    using System;
    using System.Data.SqlClient;
    using Microsoft.Data.Sqlite;
    using Microsoft.EntityFrameworkCore;
    
    
    [System.ComponentModel.DataAnnotations.Schema.TableAttribute("sys_external_file_formats")]
    public partial class SysExternalFileFormatCatalog
    {
        
        private System.Nullable<int> _file_format_id;
        
        private string _name;
        
        private string _format_type;
        
        private string _field_terminator;
        
        private string _string_delimiter;
        
        private string _date_format;
        
        private System.Nullable<bool> _use_type_default;
        
        private string _serde_method;
        
        private string _row_terminator;
        
        private string _encoding;
        
        private string _data_compression;
        
        private System.Nullable<int> _first_row;
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("file_format_id")]
        public System.Nullable<int> FileFormatId
        {
            get
            {
                return this._file_format_id;
            }
            set
            {
                this._file_format_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("name")]
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("format_type")]
        public string FormatType
        {
            get
            {
                return this._format_type;
            }
            set
            {
                this._format_type = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("field_terminator")]
        public string FieldTerminator
        {
            get
            {
                return this._field_terminator;
            }
            set
            {
                this._field_terminator = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("string_delimiter")]
        public string StringDelimiter
        {
            get
            {
                return this._string_delimiter;
            }
            set
            {
                this._string_delimiter = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("date_format")]
        public string DateFormat
        {
            get
            {
                return this._date_format;
            }
            set
            {
                this._date_format = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("use_type_default")]
        public System.Nullable<bool> UseTypeDefault
        {
            get
            {
                return this._use_type_default;
            }
            set
            {
                this._use_type_default = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("serde_method")]
        public string SerdeMethod
        {
            get
            {
                return this._serde_method;
            }
            set
            {
                this._serde_method = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("row_terminator")]
        public string RowTerminator
        {
            get
            {
                return this._row_terminator;
            }
            set
            {
                this._row_terminator = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("encoding")]
        public string Encoding
        {
            get
            {
                return this._encoding;
            }
            set
            {
                this._encoding = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("data_compression")]
        public string DataCompression
        {
            get
            {
                return this._data_compression;
            }
            set
            {
                this._data_compression = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("first_row")]
        public System.Nullable<int> FirstRow
        {
            get
            {
                return this._first_row;
            }
            set
            {
                this._first_row = value;
            }
        }
    }
}
