//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SqlServer.CatalogStore
{
    using System;
    using System.Data.SqlClient;
    using Microsoft.Data.Sqlite;
    using Microsoft.EntityFrameworkCore;
    
    
    [System.ComponentModel.DataAnnotations.Schema.TableAttribute("sys_external_data_sources")]
    public partial class SysExternalDatumSourceCatalog
    {
        
        private System.Nullable<int> _data_source_id;
        
        private string _name;
        
        private string _location;
        
        private string _type_desc;
        
        private System.Nullable<byte> _type;
        
        private string _resource_manager_location;
        
        private System.Nullable<int> _credential_id;
        
        private string _database_name;
        
        private string _shard_map_name;
        
        private string _connection_options;
        
        private string _pushdown;
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("data_source_id")]
        public System.Nullable<int> DataSourceId
        {
            get
            {
                return this._data_source_id;
            }
            set
            {
                this._data_source_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("name")]
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("location")]
        public string Location
        {
            get
            {
                return this._location;
            }
            set
            {
                this._location = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("type_desc")]
        public string TypeDesc
        {
            get
            {
                return this._type_desc;
            }
            set
            {
                this._type_desc = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("type")]
        public System.Nullable<byte> Type
        {
            get
            {
                return this._type;
            }
            set
            {
                this._type = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("resource_manager_location")]
        public string ResourceManagerLocation
        {
            get
            {
                return this._resource_manager_location;
            }
            set
            {
                this._resource_manager_location = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("credential_id")]
        public System.Nullable<int> CredentialId
        {
            get
            {
                return this._credential_id;
            }
            set
            {
                this._credential_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("database_name")]
        public string DatabaseName
        {
            get
            {
                return this._database_name;
            }
            set
            {
                this._database_name = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("shard_map_name")]
        public string ShardMapName
        {
            get
            {
                return this._shard_map_name;
            }
            set
            {
                this._shard_map_name = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("connection_options")]
        public string ConnectionOptions
        {
            get
            {
                return this._connection_options;
            }
            set
            {
                this._connection_options = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("pushdown")]
        public string Pushdown
        {
            get
            {
                return this._pushdown;
            }
            set
            {
                this._pushdown = value;
            }
        }
    }
}
