//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SqlServer.CatalogStore
{
    using System;
    using System.Data.SqlClient;
    using Microsoft.Data.Sqlite;
    using Microsoft.EntityFrameworkCore;
    
    
    [System.ComponentModel.DataAnnotations.Schema.TableAttribute("sys_fulltext_indexes")]
    public partial class SysFulltextIndexCatalog
    {
        
        private System.Nullable<int> _object_id;
        
        private System.Nullable<int> _unique_index_id;
        
        private System.Nullable<int> _fulltext_catalog_id;
        
        private System.Nullable<bool> _is_enabled;
        
        private string _change_tracking_state;
        
        private string _change_tracking_state_desc;
        
        private System.Nullable<bool> _has_crawl_completed;
        
        private string _crawl_type;
        
        private string _crawl_type_desc;
        
        private System.Nullable<System.DateTime> _crawl_start_date;
        
        private System.Nullable<System.DateTime> _crawl_end_date;
        
        private byte[] _incremental_timestamp;
        
        private System.Nullable<int> _stoplist_id;
        
        private System.Nullable<int> _property_list_id;
        
        private System.Nullable<int> _data_space_id;
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("object_id")]
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public System.Nullable<int> ObjectId
        {
            get
            {
                return this._object_id;
            }
            set
            {
                this._object_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("unique_index_id")]
        public System.Nullable<int> UniqueIndexId
        {
            get
            {
                return this._unique_index_id;
            }
            set
            {
                this._unique_index_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("fulltext_catalog_id")]
        public System.Nullable<int> FulltextCatalogId
        {
            get
            {
                return this._fulltext_catalog_id;
            }
            set
            {
                this._fulltext_catalog_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("is_enabled")]
        public System.Nullable<bool> IsEnabled
        {
            get
            {
                return this._is_enabled;
            }
            set
            {
                this._is_enabled = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("change_tracking_state")]
        public string ChangeTrackingState
        {
            get
            {
                return this._change_tracking_state;
            }
            set
            {
                this._change_tracking_state = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("change_tracking_state_desc")]
        public string ChangeTrackingStateDesc
        {
            get
            {
                return this._change_tracking_state_desc;
            }
            set
            {
                this._change_tracking_state_desc = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("has_crawl_completed")]
        public System.Nullable<bool> HasCrawlCompleted
        {
            get
            {
                return this._has_crawl_completed;
            }
            set
            {
                this._has_crawl_completed = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("crawl_type")]
        public string CrawlType
        {
            get
            {
                return this._crawl_type;
            }
            set
            {
                this._crawl_type = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("crawl_type_desc")]
        public string CrawlTypeDesc
        {
            get
            {
                return this._crawl_type_desc;
            }
            set
            {
                this._crawl_type_desc = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("crawl_start_date")]
        public System.Nullable<System.DateTime> CrawlStartDate
        {
            get
            {
                return this._crawl_start_date;
            }
            set
            {
                this._crawl_start_date = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("crawl_end_date")]
        public System.Nullable<System.DateTime> CrawlEndDate
        {
            get
            {
                return this._crawl_end_date;
            }
            set
            {
                this._crawl_end_date = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("incremental_timestamp")]
        public byte[] IncrementalTimestamp
        {
            get
            {
                return this._incremental_timestamp;
            }
            set
            {
                this._incremental_timestamp = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("stoplist_id")]
        public System.Nullable<int> StoplistId
        {
            get
            {
                return this._stoplist_id;
            }
            set
            {
                this._stoplist_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("property_list_id")]
        public System.Nullable<int> PropertyListId
        {
            get
            {
                return this._property_list_id;
            }
            set
            {
                this._property_list_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("data_space_id")]
        public System.Nullable<int> DataSpaceId
        {
            get
            {
                return this._data_space_id;
            }
            set
            {
                this._data_space_id = value;
            }
        }
    }
}
