//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SqlServer.CatalogStore
{
    using System;
    using System.Data.SqlClient;
    using Microsoft.Data.Sqlite;
    using Microsoft.EntityFrameworkCore;
    
    
    [System.ComponentModel.DataAnnotations.Schema.TableAttribute("sys_function_order_columns")]
    public partial class SysFunctionOrderColumnCatalog
    {
        
        private System.Nullable<int> _object_id;
        
        private System.Nullable<int> _order_column_id;
        
        private System.Nullable<int> _column_id;
        
        private System.Nullable<bool> _is_descending;
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("object_id")]
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public System.Nullable<int> ObjectId
        {
            get
            {
                return this._object_id;
            }
            set
            {
                this._object_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("order_column_id")]
        public System.Nullable<int> OrderColumnId
        {
            get
            {
                return this._order_column_id;
            }
            set
            {
                this._order_column_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("column_id")]
        public System.Nullable<int> ColumnId
        {
            get
            {
                return this._column_id;
            }
            set
            {
                this._column_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("is_descending")]
        public System.Nullable<bool> IsDescending
        {
            get
            {
                return this._is_descending;
            }
            set
            {
                this._is_descending = value;
            }
        }
    }
}
