//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SqlServer.CatalogStore
{
    using System;
    using System.Data.SqlClient;
    using Microsoft.Data.Sqlite;
    using Microsoft.EntityFrameworkCore;
    
    
    [System.ComponentModel.DataAnnotations.Schema.TableAttribute("sys_foreign_keys")]
    public partial class SysForeignKeyCatalog
    {
        
        private string _name;
        
        private System.Nullable<int> _object_id;
        
        private System.Nullable<int> _principal_id;
        
        private System.Nullable<int> _schema_id;
        
        private System.Nullable<int> _parent_object_id;
        
        private string _type;
        
        private string _type_desc;
        
        private System.Nullable<System.DateTime> _create_date;
        
        private System.Nullable<System.DateTime> _modify_date;
        
        private System.Nullable<bool> _is_ms_shipped;
        
        private System.Nullable<bool> _is_published;
        
        private System.Nullable<bool> _is_schema_published;
        
        private System.Nullable<int> _referenced_object_id;
        
        private System.Nullable<int> _key_index_id;
        
        private System.Nullable<bool> _is_disabled;
        
        private System.Nullable<bool> _is_not_for_replication;
        
        private System.Nullable<bool> _is_not_trusted;
        
        private System.Nullable<byte> _delete_referential_action;
        
        private string _delete_referential_action_desc;
        
        private System.Nullable<byte> _update_referential_action;
        
        private string _update_referential_action_desc;
        
        private System.Nullable<bool> _is_system_named;
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("name")]
        public string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("object_id")]
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public System.Nullable<int> ObjectId
        {
            get
            {
                return this._object_id;
            }
            set
            {
                this._object_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("principal_id")]
        public System.Nullable<int> PrincipalId
        {
            get
            {
                return this._principal_id;
            }
            set
            {
                this._principal_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("schema_id")]
        public System.Nullable<int> SchemaId
        {
            get
            {
                return this._schema_id;
            }
            set
            {
                this._schema_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("parent_object_id")]
        public System.Nullable<int> ParentObjectId
        {
            get
            {
                return this._parent_object_id;
            }
            set
            {
                this._parent_object_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("type")]
        public string Type
        {
            get
            {
                return this._type;
            }
            set
            {
                this._type = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("type_desc")]
        public string TypeDesc
        {
            get
            {
                return this._type_desc;
            }
            set
            {
                this._type_desc = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("create_date")]
        public System.Nullable<System.DateTime> CreateDate
        {
            get
            {
                return this._create_date;
            }
            set
            {
                this._create_date = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("modify_date")]
        public System.Nullable<System.DateTime> ModifyDate
        {
            get
            {
                return this._modify_date;
            }
            set
            {
                this._modify_date = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("is_ms_shipped")]
        public System.Nullable<bool> IsMsShipped
        {
            get
            {
                return this._is_ms_shipped;
            }
            set
            {
                this._is_ms_shipped = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("is_published")]
        public System.Nullable<bool> IsPublished
        {
            get
            {
                return this._is_published;
            }
            set
            {
                this._is_published = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("is_schema_published")]
        public System.Nullable<bool> IsSchemaPublished
        {
            get
            {
                return this._is_schema_published;
            }
            set
            {
                this._is_schema_published = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("referenced_object_id")]
        public System.Nullable<int> ReferencedObjectId
        {
            get
            {
                return this._referenced_object_id;
            }
            set
            {
                this._referenced_object_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("key_index_id")]
        public System.Nullable<int> KeyIndexId
        {
            get
            {
                return this._key_index_id;
            }
            set
            {
                this._key_index_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("is_disabled")]
        public System.Nullable<bool> IsDisabled
        {
            get
            {
                return this._is_disabled;
            }
            set
            {
                this._is_disabled = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("is_not_for_replication")]
        public System.Nullable<bool> IsNotForReplication
        {
            get
            {
                return this._is_not_for_replication;
            }
            set
            {
                this._is_not_for_replication = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("is_not_trusted")]
        public System.Nullable<bool> IsNotTrusted
        {
            get
            {
                return this._is_not_trusted;
            }
            set
            {
                this._is_not_trusted = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("delete_referential_action")]
        public System.Nullable<byte> DeleteReferentialAction
        {
            get
            {
                return this._delete_referential_action;
            }
            set
            {
                this._delete_referential_action = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("delete_referential_action_desc")]
        public string DeleteReferentialActionDesc
        {
            get
            {
                return this._delete_referential_action_desc;
            }
            set
            {
                this._delete_referential_action_desc = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("update_referential_action")]
        public System.Nullable<byte> UpdateReferentialAction
        {
            get
            {
                return this._update_referential_action;
            }
            set
            {
                this._update_referential_action = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("update_referential_action_desc")]
        public string UpdateReferentialActionDesc
        {
            get
            {
                return this._update_referential_action_desc;
            }
            set
            {
                this._update_referential_action_desc = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("is_system_named")]
        public System.Nullable<bool> IsSystemNamed
        {
            get
            {
                return this._is_system_named;
            }
            set
            {
                this._is_system_named = value;
            }
        }
    }
}
