//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SqlServer.CatalogStore
{
    using System;
    using System.Data.SqlClient;
    using Microsoft.Data.Sqlite;
    using Microsoft.EntityFrameworkCore;
    
    
    [System.ComponentModel.DataAnnotations.Schema.TableAttribute("sys_foreign_key_columns")]
    public partial class SysForeignKeyColumnCatalog
    {
        
        private System.Nullable<int> _constraint_object_id;
        
        private System.Nullable<int> _constraint_column_id;
        
        private System.Nullable<int> _parent_object_id;
        
        private System.Nullable<int> _parent_column_id;
        
        private System.Nullable<int> _referenced_object_id;
        
        private System.Nullable<int> _referenced_column_id;
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("constraint_object_id")]
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public System.Nullable<int> ConstraintObjectId
        {
            get
            {
                return this._constraint_object_id;
            }
            set
            {
                this._constraint_object_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("constraint_column_id")]
        public System.Nullable<int> ConstraintColumnId
        {
            get
            {
                return this._constraint_column_id;
            }
            set
            {
                this._constraint_column_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("parent_object_id")]
        public System.Nullable<int> ParentObjectId
        {
            get
            {
                return this._parent_object_id;
            }
            set
            {
                this._parent_object_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("parent_column_id")]
        public System.Nullable<int> ParentColumnId
        {
            get
            {
                return this._parent_column_id;
            }
            set
            {
                this._parent_column_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("referenced_object_id")]
        public System.Nullable<int> ReferencedObjectId
        {
            get
            {
                return this._referenced_object_id;
            }
            set
            {
                this._referenced_object_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("referenced_column_id")]
        public System.Nullable<int> ReferencedColumnId
        {
            get
            {
                return this._referenced_column_id;
            }
            set
            {
                this._referenced_column_id = value;
            }
        }
    }
}
