//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SqlServer.CatalogStore
{
    using System;
    using System.Data.SqlClient;
    using Microsoft.Data.Sqlite;
    using Microsoft.EntityFrameworkCore;
    
    
    [System.ComponentModel.DataAnnotations.Schema.TableAttribute("sys_fulltext_index_columns")]
    public partial class SysFulltextIndexColumnCatalog
    {
        
        private System.Nullable<int> _object_id;
        
        private System.Nullable<int> _column_id;
        
        private System.Nullable<int> _type_column_id;
        
        private System.Nullable<int> _language_id;
        
        private System.Nullable<int> _statistical_semantics;
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("object_id")]
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public System.Nullable<int> ObjectId
        {
            get
            {
                return this._object_id;
            }
            set
            {
                this._object_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("column_id")]
        public System.Nullable<int> ColumnId
        {
            get
            {
                return this._column_id;
            }
            set
            {
                this._column_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("type_column_id")]
        public System.Nullable<int> TypeColumnId
        {
            get
            {
                return this._type_column_id;
            }
            set
            {
                this._type_column_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("language_id")]
        public System.Nullable<int> LanguageId
        {
            get
            {
                return this._language_id;
            }
            set
            {
                this._language_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("statistical_semantics")]
        public System.Nullable<int> StatisticalSemantics
        {
            get
            {
                return this._statistical_semantics;
            }
            set
            {
                this._statistical_semantics = value;
            }
        }
    }
}
