//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SqlServer.CatalogStore
{
    using System;
    using System.Data.SqlClient;
    using Microsoft.Data.Sqlite;
    using Microsoft.EntityFrameworkCore;
    
    
    [System.ComponentModel.DataAnnotations.Schema.TableAttribute("sys_key_encryptions")]
    public partial class SysKeyEncryptionCatalog
    {
        
        private System.Nullable<int> _key_id;
        
        private byte[] _thumbprint;
        
        private string _crypt_type;
        
        private string _crypt_type_desc;
        
        private byte[] _crypt_property;
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("key_id")]
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public System.Nullable<int> KeyId
        {
            get
            {
                return this._key_id;
            }
            set
            {
                this._key_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("thumbprint")]
        public byte[] Thumbprint
        {
            get
            {
                return this._thumbprint;
            }
            set
            {
                this._thumbprint = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("crypt_type")]
        public string CryptType
        {
            get
            {
                return this._crypt_type;
            }
            set
            {
                this._crypt_type = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("crypt_type_desc")]
        public string CryptTypeDesc
        {
            get
            {
                return this._crypt_type_desc;
            }
            set
            {
                this._crypt_type_desc = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("crypt_property")]
        public byte[] CryptProperty
        {
            get
            {
                return this._crypt_property;
            }
            set
            {
                this._crypt_property = value;
            }
        }
    }
}
