//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SqlServer.CatalogStore
{
    using System;
    using System.Data.SqlClient;
    using Microsoft.Data.Sqlite;
    using Microsoft.EntityFrameworkCore;
    
    
    [System.ComponentModel.DataAnnotations.Schema.TableAttribute("sys_numbered_procedures")]
    public partial class SysNumberedProcedureCatalog
    {
        
        private System.Nullable<int> _object_id;
        
        private System.Nullable<short> _procedure_number;
        
        private string _definition;
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("object_id")]
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public System.Nullable<int> ObjectId
        {
            get
            {
                return this._object_id;
            }
            set
            {
                this._object_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("procedure_number")]
        public System.Nullable<short> ProcedureNumber
        {
            get
            {
                return this._procedure_number;
            }
            set
            {
                this._procedure_number = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("definition")]
        public string Definition
        {
            get
            {
                return this._definition;
            }
            set
            {
                this._definition = value;
            }
        }
    }
}
