//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SqlServer.CatalogStore
{
    using System;
    using System.Data.SqlClient;
    using Microsoft.Data.Sqlite;
    using Microsoft.EntityFrameworkCore;
    
    
    [System.ComponentModel.DataAnnotations.Schema.TableAttribute("sys_periods")]
    public partial class SysPeriodCatalog
    {
        
        private string _name;
        
        private System.Nullable<byte> _period_type;
        
        private string _period_type_desc;
        
        private System.Nullable<int> _object_id;
        
        private System.Nullable<int> _start_column_id;
        
        private System.Nullable<int> _end_column_id;
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("name")]
        public string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("period_type")]
        public System.Nullable<byte> PeriodType
        {
            get
            {
                return this._period_type;
            }
            set
            {
                this._period_type = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("period_type_desc")]
        public string PeriodTypeDesc
        {
            get
            {
                return this._period_type_desc;
            }
            set
            {
                this._period_type_desc = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("object_id")]
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public System.Nullable<int> ObjectId
        {
            get
            {
                return this._object_id;
            }
            set
            {
                this._object_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("start_column_id")]
        public System.Nullable<int> StartColumnId
        {
            get
            {
                return this._start_column_id;
            }
            set
            {
                this._start_column_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("end_column_id")]
        public System.Nullable<int> EndColumnId
        {
            get
            {
                return this._end_column_id;
            }
            set
            {
                this._end_column_id = value;
            }
        }
    }
}
