//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SqlServer.CatalogStore
{
    using System;
    using System.Data.SqlClient;
    using Microsoft.Data.Sqlite;
    using Microsoft.EntityFrameworkCore;
    
    
    [System.ComponentModel.DataAnnotations.Schema.TableAttribute("sys_partitions")]
    public partial class SysPartitionCatalog
    {
        
        private System.Nullable<long> _partition_id;
        
        private System.Nullable<int> _object_id;
        
        private System.Nullable<int> _index_id;
        
        private System.Nullable<int> _partition_number;
        
        private System.Nullable<long> _hobt_id;
        
        private System.Nullable<long> _rows;
        
        private System.Nullable<short> _filestream_filegroup_id;
        
        private System.Nullable<byte> _data_compression;
        
        private string _data_compression_desc;
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("partition_id")]
        public System.Nullable<long> PartitionId
        {
            get
            {
                return this._partition_id;
            }
            set
            {
                this._partition_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("object_id")]
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public System.Nullable<int> ObjectId
        {
            get
            {
                return this._object_id;
            }
            set
            {
                this._object_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("index_id")]
        public System.Nullable<int> IndexId
        {
            get
            {
                return this._index_id;
            }
            set
            {
                this._index_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("partition_number")]
        public System.Nullable<int> PartitionNumber
        {
            get
            {
                return this._partition_number;
            }
            set
            {
                this._partition_number = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("hobt_id")]
        public System.Nullable<long> HobtId
        {
            get
            {
                return this._hobt_id;
            }
            set
            {
                this._hobt_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("rows")]
        public System.Nullable<long> Rows
        {
            get
            {
                return this._rows;
            }
            set
            {
                this._rows = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("filestream_filegroup_id")]
        public System.Nullable<short> FilestreamFilegroupId
        {
            get
            {
                return this._filestream_filegroup_id;
            }
            set
            {
                this._filestream_filegroup_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("data_compression")]
        public System.Nullable<byte> DataCompression
        {
            get
            {
                return this._data_compression;
            }
            set
            {
                this._data_compression = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("data_compression_desc")]
        public string DataCompressionDesc
        {
            get
            {
                return this._data_compression_desc;
            }
            set
            {
                this._data_compression_desc = value;
            }
        }
    }
}
