//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SqlServer.CatalogStore
{
    using System;
    using System.Data.SqlClient;
    using Microsoft.Data.Sqlite;
    using Microsoft.EntityFrameworkCore;
    
    
    [System.ComponentModel.DataAnnotations.Schema.TableAttribute("sys_procedures")]
    public partial class SysProcedureCatalog
    {
        
        private string _name;
        
        private System.Nullable<int> _object_id;
        
        private System.Nullable<int> _principal_id;
        
        private System.Nullable<int> _schema_id;
        
        private System.Nullable<int> _parent_object_id;
        
        private string _type;
        
        private string _type_desc;
        
        private System.Nullable<System.DateTime> _create_date;
        
        private System.Nullable<System.DateTime> _modify_date;
        
        private System.Nullable<bool> _is_ms_shipped;
        
        private System.Nullable<bool> _is_published;
        
        private System.Nullable<bool> _is_schema_published;
        
        private System.Nullable<bool> _is_auto_executed;
        
        private System.Nullable<bool> _is_execution_replicated;
        
        private System.Nullable<bool> _is_repl_serializable_only;
        
        private System.Nullable<bool> _skips_repl_constraints;
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("name")]
        public string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("object_id")]
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public System.Nullable<int> ObjectId
        {
            get
            {
                return this._object_id;
            }
            set
            {
                this._object_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("principal_id")]
        public System.Nullable<int> PrincipalId
        {
            get
            {
                return this._principal_id;
            }
            set
            {
                this._principal_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("schema_id")]
        public System.Nullable<int> SchemaId
        {
            get
            {
                return this._schema_id;
            }
            set
            {
                this._schema_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("parent_object_id")]
        public System.Nullable<int> ParentObjectId
        {
            get
            {
                return this._parent_object_id;
            }
            set
            {
                this._parent_object_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("type")]
        public string Type
        {
            get
            {
                return this._type;
            }
            set
            {
                this._type = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("type_desc")]
        public string TypeDesc
        {
            get
            {
                return this._type_desc;
            }
            set
            {
                this._type_desc = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("create_date")]
        public System.Nullable<System.DateTime> CreateDate
        {
            get
            {
                return this._create_date;
            }
            set
            {
                this._create_date = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("modify_date")]
        public System.Nullable<System.DateTime> ModifyDate
        {
            get
            {
                return this._modify_date;
            }
            set
            {
                this._modify_date = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("is_ms_shipped")]
        public System.Nullable<bool> IsMsShipped
        {
            get
            {
                return this._is_ms_shipped;
            }
            set
            {
                this._is_ms_shipped = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("is_published")]
        public System.Nullable<bool> IsPublished
        {
            get
            {
                return this._is_published;
            }
            set
            {
                this._is_published = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("is_schema_published")]
        public System.Nullable<bool> IsSchemaPublished
        {
            get
            {
                return this._is_schema_published;
            }
            set
            {
                this._is_schema_published = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("is_auto_executed")]
        public System.Nullable<bool> IsAutoExecuted
        {
            get
            {
                return this._is_auto_executed;
            }
            set
            {
                this._is_auto_executed = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("is_execution_replicated")]
        public System.Nullable<bool> IsExecutionReplicated
        {
            get
            {
                return this._is_execution_replicated;
            }
            set
            {
                this._is_execution_replicated = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("is_repl_serializable_only")]
        public System.Nullable<bool> IsReplSerializableOnly
        {
            get
            {
                return this._is_repl_serializable_only;
            }
            set
            {
                this._is_repl_serializable_only = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("skips_repl_constraints")]
        public System.Nullable<bool> SkipsReplConstraints
        {
            get
            {
                return this._skips_repl_constraints;
            }
            set
            {
                this._skips_repl_constraints = value;
            }
        }
    }
}
