//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SqlServer.CatalogStore
{
    using System;
    using System.Data.SqlClient;
    using Microsoft.Data.Sqlite;
    using Microsoft.EntityFrameworkCore;
    
    
    [System.ComponentModel.DataAnnotations.Schema.TableAttribute("sys_partition_functions")]
    public partial class SysPartitionFunctionCatalog
    {
        
        private string _name;
        
        private System.Nullable<int> _function_id;
        
        private string _type;
        
        private string _type_desc;
        
        private System.Nullable<int> _fanout;
        
        private System.Nullable<bool> _boundary_value_on_right;
        
        private System.Nullable<bool> _is_system;
        
        private System.Nullable<System.DateTime> _create_date;
        
        private System.Nullable<System.DateTime> _modify_date;
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("name")]
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("function_id")]
        public System.Nullable<int> FunctionId
        {
            get
            {
                return this._function_id;
            }
            set
            {
                this._function_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("type")]
        public string Type
        {
            get
            {
                return this._type;
            }
            set
            {
                this._type = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("type_desc")]
        public string TypeDesc
        {
            get
            {
                return this._type_desc;
            }
            set
            {
                this._type_desc = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("fanout")]
        public System.Nullable<int> Fanout
        {
            get
            {
                return this._fanout;
            }
            set
            {
                this._fanout = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("boundary_value_on_right")]
        public System.Nullable<bool> BoundaryValueOnRight
        {
            get
            {
                return this._boundary_value_on_right;
            }
            set
            {
                this._boundary_value_on_right = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("is_system")]
        public System.Nullable<bool> IsSystem
        {
            get
            {
                return this._is_system;
            }
            set
            {
                this._is_system = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("create_date")]
        public System.Nullable<System.DateTime> CreateDate
        {
            get
            {
                return this._create_date;
            }
            set
            {
                this._create_date = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("modify_date")]
        public System.Nullable<System.DateTime> ModifyDate
        {
            get
            {
                return this._modify_date;
            }
            set
            {
                this._modify_date = value;
            }
        }
    }
}
