//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SqlServer.CatalogStore
{
    using System;
    using System.Data.SqlClient;
    using Microsoft.Data.Sqlite;
    using Microsoft.EntityFrameworkCore;
    
    
    [System.ComponentModel.DataAnnotations.Schema.TableAttribute("sys_parameters")]
    public partial class SysParameterCatalog
    {
        
        private System.Nullable<int> _object_id;
        
        private string _name;
        
        private System.Nullable<int> _parameter_id;
        
        private System.Nullable<byte> _system_type_id;
        
        private System.Nullable<int> _user_type_id;
        
        private System.Nullable<short> _max_length;
        
        private System.Nullable<byte> _precision;
        
        private System.Nullable<byte> _scale;
        
        private System.Nullable<bool> _is_output;
        
        private System.Nullable<bool> _is_cursor_ref;
        
        private System.Nullable<bool> _has_default_value;
        
        private System.Nullable<bool> _is_xml_document;
        
        private object _default_value;
        
        private System.Nullable<int> _xml_collection_id;
        
        private System.Nullable<bool> _is_readonly;
        
        private System.Nullable<bool> _is_nullable;
        
        private System.Nullable<int> _encryption_type;
        
        private string _encryption_type_desc;
        
        private string _encryption_algorithm_name;
        
        private System.Nullable<int> _column_encryption_key_id;
        
        private string _column_encryption_key_database_name;
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("object_id")]
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public System.Nullable<int> ObjectId
        {
            get
            {
                return this._object_id;
            }
            set
            {
                this._object_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("name")]
        public string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("parameter_id")]
        public System.Nullable<int> ParameterId
        {
            get
            {
                return this._parameter_id;
            }
            set
            {
                this._parameter_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("system_type_id")]
        public System.Nullable<byte> SystemTypeId
        {
            get
            {
                return this._system_type_id;
            }
            set
            {
                this._system_type_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("user_type_id")]
        public System.Nullable<int> UserTypeId
        {
            get
            {
                return this._user_type_id;
            }
            set
            {
                this._user_type_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("max_length")]
        public System.Nullable<short> MaxLength
        {
            get
            {
                return this._max_length;
            }
            set
            {
                this._max_length = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("precision")]
        public System.Nullable<byte> Precision
        {
            get
            {
                return this._precision;
            }
            set
            {
                this._precision = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("scale")]
        public System.Nullable<byte> Scale
        {
            get
            {
                return this._scale;
            }
            set
            {
                this._scale = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("is_output")]
        public System.Nullable<bool> IsOutput
        {
            get
            {
                return this._is_output;
            }
            set
            {
                this._is_output = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("is_cursor_ref")]
        public System.Nullable<bool> IsCursorRef
        {
            get
            {
                return this._is_cursor_ref;
            }
            set
            {
                this._is_cursor_ref = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("has_default_value")]
        public System.Nullable<bool> HasDefaultValue
        {
            get
            {
                return this._has_default_value;
            }
            set
            {
                this._has_default_value = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("is_xml_document")]
        public System.Nullable<bool> IsXmlDocument
        {
            get
            {
                return this._is_xml_document;
            }
            set
            {
                this._is_xml_document = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.NotMappedAttribute()]
        public object DefaultValue
        {
            get
            {
                return this._default_value;
            }
            set
            {
                this._default_value = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("xml_collection_id")]
        public System.Nullable<int> XmlCollectionId
        {
            get
            {
                return this._xml_collection_id;
            }
            set
            {
                this._xml_collection_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("is_readonly")]
        public System.Nullable<bool> IsReadonly
        {
            get
            {
                return this._is_readonly;
            }
            set
            {
                this._is_readonly = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("is_nullable")]
        public System.Nullable<bool> IsNullable
        {
            get
            {
                return this._is_nullable;
            }
            set
            {
                this._is_nullable = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("encryption_type")]
        public System.Nullable<int> EncryptionType
        {
            get
            {
                return this._encryption_type;
            }
            set
            {
                this._encryption_type = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("encryption_type_desc")]
        public string EncryptionTypeDesc
        {
            get
            {
                return this._encryption_type_desc;
            }
            set
            {
                this._encryption_type_desc = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("encryption_algorithm_name")]
        public string EncryptionAlgorithmName
        {
            get
            {
                return this._encryption_algorithm_name;
            }
            set
            {
                this._encryption_algorithm_name = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("column_encryption_key_id")]
        public System.Nullable<int> ColumnEncryptionKeyId
        {
            get
            {
                return this._column_encryption_key_id;
            }
            set
            {
                this._column_encryption_key_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("column_encryption_key_database_name")]
        public string ColumnEncryptionKeyDatabaseName
        {
            get
            {
                return this._column_encryption_key_database_name;
            }
            set
            {
                this._column_encryption_key_database_name = value;
            }
        }
    }
}
