//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SqlServer.CatalogStore
{
    using System;
    using System.Data.SqlClient;
    using Microsoft.Data.Sqlite;
    using Microsoft.EntityFrameworkCore;
    
    
    [System.ComponentModel.DataAnnotations.Schema.TableAttribute("sys_remote_service_bindings")]
    public partial class SysRemoteServiceBindingCatalog
    {
        
        private string _name;
        
        private System.Nullable<int> _remote_service_binding_id;
        
        private System.Nullable<int> _principal_id;
        
        private string _remote_service_name;
        
        private System.Nullable<int> _service_contract_id;
        
        private System.Nullable<int> _remote_principal_id;
        
        private System.Nullable<bool> _is_anonymous_on;
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("name")]
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("remote_service_binding_id")]
        public System.Nullable<int> RemoteServiceBindingId
        {
            get
            {
                return this._remote_service_binding_id;
            }
            set
            {
                this._remote_service_binding_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("principal_id")]
        public System.Nullable<int> PrincipalId
        {
            get
            {
                return this._principal_id;
            }
            set
            {
                this._principal_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("remote_service_name")]
        public string RemoteServiceName
        {
            get
            {
                return this._remote_service_name;
            }
            set
            {
                this._remote_service_name = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("service_contract_id")]
        public System.Nullable<int> ServiceContractId
        {
            get
            {
                return this._service_contract_id;
            }
            set
            {
                this._service_contract_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("remote_principal_id")]
        public System.Nullable<int> RemotePrincipalId
        {
            get
            {
                return this._remote_principal_id;
            }
            set
            {
                this._remote_principal_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("is_anonymous_on")]
        public System.Nullable<bool> IsAnonymousOn
        {
            get
            {
                return this._is_anonymous_on;
            }
            set
            {
                this._is_anonymous_on = value;
            }
        }
    }
}
