//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SqlServer.CatalogStore
{
    using System;
    using System.Data.SqlClient;
    using Microsoft.Data.Sqlite;
    using Microsoft.EntityFrameworkCore;
    
    
    [System.ComponentModel.DataAnnotations.Schema.TableAttribute("sys_routes")]
    public partial class SysRouteCatalog
    {
        
        private string _name;
        
        private System.Nullable<int> _route_id;
        
        private System.Nullable<int> _principal_id;
        
        private string _remote_service_name;
        
        private string _broker_instance;
        
        private System.Nullable<System.DateTime> _lifetime;
        
        private string _address;
        
        private string _mirror_address;
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("name")]
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("route_id")]
        public System.Nullable<int> RouteId
        {
            get
            {
                return this._route_id;
            }
            set
            {
                this._route_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("principal_id")]
        public System.Nullable<int> PrincipalId
        {
            get
            {
                return this._principal_id;
            }
            set
            {
                this._principal_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("remote_service_name")]
        public string RemoteServiceName
        {
            get
            {
                return this._remote_service_name;
            }
            set
            {
                this._remote_service_name = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("broker_instance")]
        public string BrokerInstance
        {
            get
            {
                return this._broker_instance;
            }
            set
            {
                this._broker_instance = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("lifetime")]
        public System.Nullable<System.DateTime> Lifetime
        {
            get
            {
                return this._lifetime;
            }
            set
            {
                this._lifetime = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("address")]
        public string Address
        {
            get
            {
                return this._address;
            }
            set
            {
                this._address = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("mirror_address")]
        public string MirrorAddress
        {
            get
            {
                return this._mirror_address;
            }
            set
            {
                this._mirror_address = value;
            }
        }
    }
}
