//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SqlServer.CatalogStore
{
    using System;
    using System.Data.SqlClient;
    using Microsoft.Data.Sqlite;
    using Microsoft.EntityFrameworkCore;
    
    
    [System.ComponentModel.DataAnnotations.Schema.TableAttribute("sys_registered_search_properties")]
    public partial class SysRegisteredSearchPropertyCatalog
    {
        
        private System.Nullable<int> _property_list_id;
        
        private System.Nullable<int> _property_id;
        
        private string _property_name;
        
        private System.Nullable<System.Guid> _property_set_guid;
        
        private System.Nullable<int> _property_int_id;
        
        private string _property_description;
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("property_list_id")]
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public System.Nullable<int> PropertyListId
        {
            get
            {
                return this._property_list_id;
            }
            set
            {
                this._property_list_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("property_id")]
        public System.Nullable<int> PropertyId
        {
            get
            {
                return this._property_id;
            }
            set
            {
                this._property_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("property_name")]
        public string PropertyName
        {
            get
            {
                return this._property_name;
            }
            set
            {
                this._property_name = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("property_set_guid")]
        public System.Nullable<System.Guid> PropertySetGuid
        {
            get
            {
                return this._property_set_guid;
            }
            set
            {
                this._property_set_guid = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("property_int_id")]
        public System.Nullable<int> PropertyIntId
        {
            get
            {
                return this._property_int_id;
            }
            set
            {
                this._property_int_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("property_description")]
        public string PropertyDescription
        {
            get
            {
                return this._property_description;
            }
            set
            {
                this._property_description = value;
            }
        }
    }
}
