//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SqlServer.CatalogStore
{
    using System;
    using System.Data.SqlClient;
    using Microsoft.Data.Sqlite;
    using Microsoft.EntityFrameworkCore;
    
    
    [System.ComponentModel.DataAnnotations.Schema.TableAttribute("sys_sql_modules")]
    public partial class SysSqlModuleCatalog
    {
        
        private System.Nullable<int> _object_id;
        
        private string _definition;
        
        private System.Nullable<bool> _uses_ansi_nulls;
        
        private System.Nullable<bool> _uses_quoted_identifier;
        
        private System.Nullable<bool> _is_schema_bound;
        
        private System.Nullable<bool> _uses_database_collation;
        
        private System.Nullable<bool> _is_recompiled;
        
        private System.Nullable<bool> _null_on_null_input;
        
        private System.Nullable<int> _execute_as_principal_id;
        
        private System.Nullable<bool> _uses_native_compilation;
        
        private System.Nullable<bool> _inline_type;
        
        private System.Nullable<bool> _is_inlineable;
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("object_id")]
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public System.Nullable<int> ObjectId
        {
            get
            {
                return this._object_id;
            }
            set
            {
                this._object_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("definition")]
        public string Definition
        {
            get
            {
                return this._definition;
            }
            set
            {
                this._definition = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("uses_ansi_nulls")]
        public System.Nullable<bool> UsesAnsiNulls
        {
            get
            {
                return this._uses_ansi_nulls;
            }
            set
            {
                this._uses_ansi_nulls = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("uses_quoted_identifier")]
        public System.Nullable<bool> UsesQuotedIdentifier
        {
            get
            {
                return this._uses_quoted_identifier;
            }
            set
            {
                this._uses_quoted_identifier = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("is_schema_bound")]
        public System.Nullable<bool> IsSchemaBound
        {
            get
            {
                return this._is_schema_bound;
            }
            set
            {
                this._is_schema_bound = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("uses_database_collation")]
        public System.Nullable<bool> UsesDatabaseCollation
        {
            get
            {
                return this._uses_database_collation;
            }
            set
            {
                this._uses_database_collation = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("is_recompiled")]
        public System.Nullable<bool> IsRecompiled
        {
            get
            {
                return this._is_recompiled;
            }
            set
            {
                this._is_recompiled = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("null_on_null_input")]
        public System.Nullable<bool> NullOnNullInput
        {
            get
            {
                return this._null_on_null_input;
            }
            set
            {
                this._null_on_null_input = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("execute_as_principal_id")]
        public System.Nullable<int> ExecuteAsPrincipalId
        {
            get
            {
                return this._execute_as_principal_id;
            }
            set
            {
                this._execute_as_principal_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("uses_native_compilation")]
        public System.Nullable<bool> UsesNativeCompilation
        {
            get
            {
                return this._uses_native_compilation;
            }
            set
            {
                this._uses_native_compilation = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("inline_type")]
        public System.Nullable<bool> InlineType
        {
            get
            {
                return this._inline_type;
            }
            set
            {
                this._inline_type = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("is_inlineable")]
        public System.Nullable<bool> IsInlineable
        {
            get
            {
                return this._is_inlineable;
            }
            set
            {
                this._is_inlineable = value;
            }
        }
    }
}
