//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SqlServer.CatalogStore
{
    using System;
    using System.Data.SqlClient;
    using Microsoft.Data.Sqlite;
    using Microsoft.EntityFrameworkCore;
    
    
    [System.ComponentModel.DataAnnotations.Schema.TableAttribute("sys_service_message_types")]
    public partial class SysServiceMessageTypeCatalog
    {
        
        private string _name;
        
        private System.Nullable<int> _message_type_id;
        
        private System.Nullable<int> _principal_id;
        
        private string _validation;
        
        private string _validation_desc;
        
        private System.Nullable<int> _xml_collection_id;
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("name")]
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("message_type_id")]
        public System.Nullable<int> MessageTypeId
        {
            get
            {
                return this._message_type_id;
            }
            set
            {
                this._message_type_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("principal_id")]
        public System.Nullable<int> PrincipalId
        {
            get
            {
                return this._principal_id;
            }
            set
            {
                this._principal_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("validation")]
        public string Validation
        {
            get
            {
                return this._validation;
            }
            set
            {
                this._validation = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("validation_desc")]
        public string ValidationDesc
        {
            get
            {
                return this._validation_desc;
            }
            set
            {
                this._validation_desc = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("xml_collection_id")]
        public System.Nullable<int> XmlCollectionId
        {
            get
            {
                return this._xml_collection_id;
            }
            set
            {
                this._xml_collection_id = value;
            }
        }
    }
}
