//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SqlServer.CatalogStore
{
    using System;
    using System.Data.SqlClient;
    using Microsoft.Data.Sqlite;
    using Microsoft.EntityFrameworkCore;
    
    
    [System.ComponentModel.DataAnnotations.Schema.TableAttribute("sys_selective_xml_index_paths")]
    public partial class SysSelectiveXmlIndexPathCatalog
    {
        
        private System.Nullable<int> _object_id;
        
        private System.Nullable<int> _index_id;
        
        private System.Nullable<int> _path_id;
        
        private string _path;
        
        private string _name;
        
        private System.Nullable<byte> _path_type;
        
        private string _path_type_desc;
        
        private System.Nullable<int> _xml_component_id;
        
        private string _xquery_type_description;
        
        private System.Nullable<bool> _is_xquery_type_inferred;
        
        private System.Nullable<int> _xquery_max_length;
        
        private System.Nullable<bool> _is_xquery_max_length_inferred;
        
        private System.Nullable<bool> _is_node;
        
        private System.Nullable<byte> _system_type_id;
        
        private System.Nullable<byte> _user_type_id;
        
        private System.Nullable<short> _max_length;
        
        private System.Nullable<byte> _precision;
        
        private System.Nullable<byte> _scale;
        
        private string _collation_name;
        
        private System.Nullable<bool> _is_singleton;
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("object_id")]
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public System.Nullable<int> ObjectId
        {
            get
            {
                return this._object_id;
            }
            set
            {
                this._object_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("index_id")]
        public System.Nullable<int> IndexId
        {
            get
            {
                return this._index_id;
            }
            set
            {
                this._index_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("path_id")]
        public System.Nullable<int> PathId
        {
            get
            {
                return this._path_id;
            }
            set
            {
                this._path_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("path")]
        public string Path
        {
            get
            {
                return this._path;
            }
            set
            {
                this._path = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("name")]
        public string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("path_type")]
        public System.Nullable<byte> PathType
        {
            get
            {
                return this._path_type;
            }
            set
            {
                this._path_type = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("path_type_desc")]
        public string PathTypeDesc
        {
            get
            {
                return this._path_type_desc;
            }
            set
            {
                this._path_type_desc = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("xml_component_id")]
        public System.Nullable<int> XmlComponentId
        {
            get
            {
                return this._xml_component_id;
            }
            set
            {
                this._xml_component_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("xquery_type_description")]
        public string XqueryTypeDescription
        {
            get
            {
                return this._xquery_type_description;
            }
            set
            {
                this._xquery_type_description = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("is_xquery_type_inferred")]
        public System.Nullable<bool> IsXqueryTypeInferred
        {
            get
            {
                return this._is_xquery_type_inferred;
            }
            set
            {
                this._is_xquery_type_inferred = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("xquery_max_length")]
        public System.Nullable<int> XqueryMaxLength
        {
            get
            {
                return this._xquery_max_length;
            }
            set
            {
                this._xquery_max_length = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("is_xquery_max_length_inferred")]
        public System.Nullable<bool> IsXqueryMaxLengthInferred
        {
            get
            {
                return this._is_xquery_max_length_inferred;
            }
            set
            {
                this._is_xquery_max_length_inferred = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("is_node")]
        public System.Nullable<bool> IsNode
        {
            get
            {
                return this._is_node;
            }
            set
            {
                this._is_node = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("system_type_id")]
        public System.Nullable<byte> SystemTypeId
        {
            get
            {
                return this._system_type_id;
            }
            set
            {
                this._system_type_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("user_type_id")]
        public System.Nullable<byte> UserTypeId
        {
            get
            {
                return this._user_type_id;
            }
            set
            {
                this._user_type_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("max_length")]
        public System.Nullable<short> MaxLength
        {
            get
            {
                return this._max_length;
            }
            set
            {
                this._max_length = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("precision")]
        public System.Nullable<byte> Precision
        {
            get
            {
                return this._precision;
            }
            set
            {
                this._precision = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("scale")]
        public System.Nullable<byte> Scale
        {
            get
            {
                return this._scale;
            }
            set
            {
                this._scale = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("collation_name")]
        public string CollationName
        {
            get
            {
                return this._collation_name;
            }
            set
            {
                this._collation_name = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("is_singleton")]
        public System.Nullable<bool> IsSingleton
        {
            get
            {
                return this._is_singleton;
            }
            set
            {
                this._is_singleton = value;
            }
        }
    }
}
