//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SqlServer.CatalogStore
{
    using System;
    using System.Data.SqlClient;
    using Microsoft.Data.Sqlite;
    using Microsoft.EntityFrameworkCore;
    
    
    [System.ComponentModel.DataAnnotations.Schema.TableAttribute("sys_server_audits")]
    public partial class SysServerAuditCatalog
    {
        
        private System.Nullable<int> _audit_id;
        
        private string _name;
        
        private System.Nullable<System.Guid> _audit_guid;
        
        private System.Nullable<System.DateTime> _create_date;
        
        private System.Nullable<System.DateTime> _modify_date;
        
        private System.Nullable<int> _principal_id;
        
        private string _type;
        
        private string _type_desc;
        
        private System.Nullable<byte> _on_failure;
        
        private string _on_failure_desc;
        
        private System.Nullable<bool> _is_state_enabled;
        
        private System.Nullable<int> _queue_delay;
        
        private string _predicate;
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("audit_id")]
        public System.Nullable<int> AuditId
        {
            get
            {
                return this._audit_id;
            }
            set
            {
                this._audit_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("name")]
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("audit_guid")]
        public System.Nullable<System.Guid> AuditGuid
        {
            get
            {
                return this._audit_guid;
            }
            set
            {
                this._audit_guid = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("create_date")]
        public System.Nullable<System.DateTime> CreateDate
        {
            get
            {
                return this._create_date;
            }
            set
            {
                this._create_date = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("modify_date")]
        public System.Nullable<System.DateTime> ModifyDate
        {
            get
            {
                return this._modify_date;
            }
            set
            {
                this._modify_date = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("principal_id")]
        public System.Nullable<int> PrincipalId
        {
            get
            {
                return this._principal_id;
            }
            set
            {
                this._principal_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("type")]
        public string Type
        {
            get
            {
                return this._type;
            }
            set
            {
                this._type = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("type_desc")]
        public string TypeDesc
        {
            get
            {
                return this._type_desc;
            }
            set
            {
                this._type_desc = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("on_failure")]
        public System.Nullable<byte> OnFailure
        {
            get
            {
                return this._on_failure;
            }
            set
            {
                this._on_failure = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("on_failure_desc")]
        public string OnFailureDesc
        {
            get
            {
                return this._on_failure_desc;
            }
            set
            {
                this._on_failure_desc = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("is_state_enabled")]
        public System.Nullable<bool> IsStateEnabled
        {
            get
            {
                return this._is_state_enabled;
            }
            set
            {
                this._is_state_enabled = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("queue_delay")]
        public System.Nullable<int> QueueDelay
        {
            get
            {
                return this._queue_delay;
            }
            set
            {
                this._queue_delay = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("predicate")]
        public string Predicate
        {
            get
            {
                return this._predicate;
            }
            set
            {
                this._predicate = value;
            }
        }
    }
}
