//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SqlServer.CatalogStore
{
    using System;
    using System.Data.SqlClient;
    using Microsoft.Data.Sqlite;
    using Microsoft.EntityFrameworkCore;
    
    
    [System.ComponentModel.DataAnnotations.Schema.TableAttribute("sys_sequences")]
    public partial class SysSequenceCatalog
    {
        
        private string _name;
        
        private System.Nullable<int> _object_id;
        
        private System.Nullable<int> _principal_id;
        
        private System.Nullable<int> _schema_id;
        
        private System.Nullable<int> _parent_object_id;
        
        private string _type;
        
        private string _type_desc;
        
        private System.Nullable<System.DateTime> _create_date;
        
        private System.Nullable<System.DateTime> _modify_date;
        
        private System.Nullable<bool> _is_ms_shipped;
        
        private System.Nullable<bool> _is_published;
        
        private System.Nullable<bool> _is_schema_published;
        
        private object _start_value;
        
        private object _increment;
        
        private object _minimum_value;
        
        private object _maximum_value;
        
        private System.Nullable<bool> _is_cycling;
        
        private System.Nullable<bool> _is_cached;
        
        private System.Nullable<int> _cache_size;
        
        private System.Nullable<byte> _system_type_id;
        
        private System.Nullable<int> _user_type_id;
        
        private System.Nullable<byte> _precision;
        
        private System.Nullable<byte> _scale;
        
        private object _current_value;
        
        private System.Nullable<bool> _is_exhausted;
        
        private object _last_used_value;
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("name")]
        public string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("object_id")]
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public System.Nullable<int> ObjectId
        {
            get
            {
                return this._object_id;
            }
            set
            {
                this._object_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("principal_id")]
        public System.Nullable<int> PrincipalId
        {
            get
            {
                return this._principal_id;
            }
            set
            {
                this._principal_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("schema_id")]
        public System.Nullable<int> SchemaId
        {
            get
            {
                return this._schema_id;
            }
            set
            {
                this._schema_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("parent_object_id")]
        public System.Nullable<int> ParentObjectId
        {
            get
            {
                return this._parent_object_id;
            }
            set
            {
                this._parent_object_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("type")]
        public string Type
        {
            get
            {
                return this._type;
            }
            set
            {
                this._type = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("type_desc")]
        public string TypeDesc
        {
            get
            {
                return this._type_desc;
            }
            set
            {
                this._type_desc = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("create_date")]
        public System.Nullable<System.DateTime> CreateDate
        {
            get
            {
                return this._create_date;
            }
            set
            {
                this._create_date = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("modify_date")]
        public System.Nullable<System.DateTime> ModifyDate
        {
            get
            {
                return this._modify_date;
            }
            set
            {
                this._modify_date = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("is_ms_shipped")]
        public System.Nullable<bool> IsMsShipped
        {
            get
            {
                return this._is_ms_shipped;
            }
            set
            {
                this._is_ms_shipped = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("is_published")]
        public System.Nullable<bool> IsPublished
        {
            get
            {
                return this._is_published;
            }
            set
            {
                this._is_published = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("is_schema_published")]
        public System.Nullable<bool> IsSchemaPublished
        {
            get
            {
                return this._is_schema_published;
            }
            set
            {
                this._is_schema_published = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.NotMappedAttribute()]
        public object StartValue
        {
            get
            {
                return this._start_value;
            }
            set
            {
                this._start_value = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.NotMappedAttribute()]
        public object Increment
        {
            get
            {
                return this._increment;
            }
            set
            {
                this._increment = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.NotMappedAttribute()]
        public object MinimumValue
        {
            get
            {
                return this._minimum_value;
            }
            set
            {
                this._minimum_value = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.NotMappedAttribute()]
        public object MaximumValue
        {
            get
            {
                return this._maximum_value;
            }
            set
            {
                this._maximum_value = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("is_cycling")]
        public System.Nullable<bool> IsCycling
        {
            get
            {
                return this._is_cycling;
            }
            set
            {
                this._is_cycling = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("is_cached")]
        public System.Nullable<bool> IsCached
        {
            get
            {
                return this._is_cached;
            }
            set
            {
                this._is_cached = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("cache_size")]
        public System.Nullable<int> CacheSize
        {
            get
            {
                return this._cache_size;
            }
            set
            {
                this._cache_size = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("system_type_id")]
        public System.Nullable<byte> SystemTypeId
        {
            get
            {
                return this._system_type_id;
            }
            set
            {
                this._system_type_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("user_type_id")]
        public System.Nullable<int> UserTypeId
        {
            get
            {
                return this._user_type_id;
            }
            set
            {
                this._user_type_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("precision")]
        public System.Nullable<byte> Precision
        {
            get
            {
                return this._precision;
            }
            set
            {
                this._precision = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("scale")]
        public System.Nullable<byte> Scale
        {
            get
            {
                return this._scale;
            }
            set
            {
                this._scale = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.NotMappedAttribute()]
        public object CurrentValue
        {
            get
            {
                return this._current_value;
            }
            set
            {
                this._current_value = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("is_exhausted")]
        public System.Nullable<bool> IsExhausted
        {
            get
            {
                return this._is_exhausted;
            }
            set
            {
                this._is_exhausted = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.NotMappedAttribute()]
        public object LastUsedValue
        {
            get
            {
                return this._last_used_value;
            }
            set
            {
                this._last_used_value = value;
            }
        }
    }
}
