//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SqlServer.CatalogStore
{
    using System;
    using System.Data.SqlClient;
    using Microsoft.Data.Sqlite;
    using Microsoft.EntityFrameworkCore;
    
    
    [System.ComponentModel.DataAnnotations.Schema.TableAttribute("sys_service_queues")]
    public partial class SysServiceQueueCatalog
    {
        
        private string _name;
        
        private System.Nullable<int> _object_id;
        
        private System.Nullable<int> _principal_id;
        
        private System.Nullable<int> _schema_id;
        
        private System.Nullable<int> _parent_object_id;
        
        private string _type;
        
        private string _type_desc;
        
        private System.Nullable<System.DateTime> _create_date;
        
        private System.Nullable<System.DateTime> _modify_date;
        
        private System.Nullable<bool> _is_ms_shipped;
        
        private System.Nullable<bool> _is_published;
        
        private System.Nullable<bool> _is_schema_published;
        
        private System.Nullable<short> _max_readers;
        
        private string _activation_procedure;
        
        private System.Nullable<int> _execute_as_principal_id;
        
        private System.Nullable<bool> _is_activation_enabled;
        
        private System.Nullable<bool> _is_receive_enabled;
        
        private System.Nullable<bool> _is_enqueue_enabled;
        
        private System.Nullable<bool> _is_retention_enabled;
        
        private System.Nullable<bool> _is_poison_message_handling_enabled;
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("name")]
        public string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("object_id")]
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public System.Nullable<int> ObjectId
        {
            get
            {
                return this._object_id;
            }
            set
            {
                this._object_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("principal_id")]
        public System.Nullable<int> PrincipalId
        {
            get
            {
                return this._principal_id;
            }
            set
            {
                this._principal_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("schema_id")]
        public System.Nullable<int> SchemaId
        {
            get
            {
                return this._schema_id;
            }
            set
            {
                this._schema_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("parent_object_id")]
        public System.Nullable<int> ParentObjectId
        {
            get
            {
                return this._parent_object_id;
            }
            set
            {
                this._parent_object_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("type")]
        public string Type
        {
            get
            {
                return this._type;
            }
            set
            {
                this._type = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("type_desc")]
        public string TypeDesc
        {
            get
            {
                return this._type_desc;
            }
            set
            {
                this._type_desc = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("create_date")]
        public System.Nullable<System.DateTime> CreateDate
        {
            get
            {
                return this._create_date;
            }
            set
            {
                this._create_date = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("modify_date")]
        public System.Nullable<System.DateTime> ModifyDate
        {
            get
            {
                return this._modify_date;
            }
            set
            {
                this._modify_date = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("is_ms_shipped")]
        public System.Nullable<bool> IsMsShipped
        {
            get
            {
                return this._is_ms_shipped;
            }
            set
            {
                this._is_ms_shipped = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("is_published")]
        public System.Nullable<bool> IsPublished
        {
            get
            {
                return this._is_published;
            }
            set
            {
                this._is_published = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("is_schema_published")]
        public System.Nullable<bool> IsSchemaPublished
        {
            get
            {
                return this._is_schema_published;
            }
            set
            {
                this._is_schema_published = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("max_readers")]
        public System.Nullable<short> MaxReaders
        {
            get
            {
                return this._max_readers;
            }
            set
            {
                this._max_readers = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("activation_procedure")]
        public string ActivationProcedure
        {
            get
            {
                return this._activation_procedure;
            }
            set
            {
                this._activation_procedure = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("execute_as_principal_id")]
        public System.Nullable<int> ExecuteAsPrincipalId
        {
            get
            {
                return this._execute_as_principal_id;
            }
            set
            {
                this._execute_as_principal_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("is_activation_enabled")]
        public System.Nullable<bool> IsActivationEnabled
        {
            get
            {
                return this._is_activation_enabled;
            }
            set
            {
                this._is_activation_enabled = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("is_receive_enabled")]
        public System.Nullable<bool> IsReceiveEnabled
        {
            get
            {
                return this._is_receive_enabled;
            }
            set
            {
                this._is_receive_enabled = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("is_enqueue_enabled")]
        public System.Nullable<bool> IsEnqueueEnabled
        {
            get
            {
                return this._is_enqueue_enabled;
            }
            set
            {
                this._is_enqueue_enabled = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("is_retention_enabled")]
        public System.Nullable<bool> IsRetentionEnabled
        {
            get
            {
                return this._is_retention_enabled;
            }
            set
            {
                this._is_retention_enabled = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("is_poison_message_handling_enabled")]
        public System.Nullable<bool> IsPoisonMessageHandlingEnabled
        {
            get
            {
                return this._is_poison_message_handling_enabled;
            }
            set
            {
                this._is_poison_message_handling_enabled = value;
            }
        }
    }
}
