//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SqlServer.CatalogStore
{
    using System;
    using System.Data.SqlClient;
    using Microsoft.Data.Sqlite;
    using Microsoft.EntityFrameworkCore;
    
    
    [System.ComponentModel.DataAnnotations.Schema.TableAttribute("sys_spatial_index_tessellations")]
    public partial class SysSpatialIndexTessellationCatalog
    {
        
        private System.Nullable<int> _object_id;
        
        private System.Nullable<int> _index_id;
        
        private string _tessellation_scheme;
        
        private System.Nullable<double> _bounding_box_xmin;
        
        private System.Nullable<double> _bounding_box_ymin;
        
        private System.Nullable<double> _bounding_box_xmax;
        
        private System.Nullable<double> _bounding_box_ymax;
        
        private System.Nullable<short> _level_1_grid;
        
        private string _level_1_grid_desc;
        
        private System.Nullable<short> _level_2_grid;
        
        private string _level_2_grid_desc;
        
        private System.Nullable<short> _level_3_grid;
        
        private string _level_3_grid_desc;
        
        private System.Nullable<short> _level_4_grid;
        
        private string _level_4_grid_desc;
        
        private System.Nullable<int> _cells_per_object;
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("object_id")]
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public System.Nullable<int> ObjectId
        {
            get
            {
                return this._object_id;
            }
            set
            {
                this._object_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("index_id")]
        public System.Nullable<int> IndexId
        {
            get
            {
                return this._index_id;
            }
            set
            {
                this._index_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("tessellation_scheme")]
        public string TessellationScheme
        {
            get
            {
                return this._tessellation_scheme;
            }
            set
            {
                this._tessellation_scheme = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("bounding_box_xmin")]
        public System.Nullable<double> BoundingBoxXmin
        {
            get
            {
                return this._bounding_box_xmin;
            }
            set
            {
                this._bounding_box_xmin = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("bounding_box_ymin")]
        public System.Nullable<double> BoundingBoxYmin
        {
            get
            {
                return this._bounding_box_ymin;
            }
            set
            {
                this._bounding_box_ymin = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("bounding_box_xmax")]
        public System.Nullable<double> BoundingBoxXmax
        {
            get
            {
                return this._bounding_box_xmax;
            }
            set
            {
                this._bounding_box_xmax = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("bounding_box_ymax")]
        public System.Nullable<double> BoundingBoxYmax
        {
            get
            {
                return this._bounding_box_ymax;
            }
            set
            {
                this._bounding_box_ymax = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("level_1_grid")]
        public System.Nullable<short> Level1Grid
        {
            get
            {
                return this._level_1_grid;
            }
            set
            {
                this._level_1_grid = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("level_1_grid_desc")]
        public string Level1GridDesc
        {
            get
            {
                return this._level_1_grid_desc;
            }
            set
            {
                this._level_1_grid_desc = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("level_2_grid")]
        public System.Nullable<short> Level2Grid
        {
            get
            {
                return this._level_2_grid;
            }
            set
            {
                this._level_2_grid = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("level_2_grid_desc")]
        public string Level2GridDesc
        {
            get
            {
                return this._level_2_grid_desc;
            }
            set
            {
                this._level_2_grid_desc = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("level_3_grid")]
        public System.Nullable<short> Level3Grid
        {
            get
            {
                return this._level_3_grid;
            }
            set
            {
                this._level_3_grid = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("level_3_grid_desc")]
        public string Level3GridDesc
        {
            get
            {
                return this._level_3_grid_desc;
            }
            set
            {
                this._level_3_grid_desc = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("level_4_grid")]
        public System.Nullable<short> Level4Grid
        {
            get
            {
                return this._level_4_grid;
            }
            set
            {
                this._level_4_grid = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("level_4_grid_desc")]
        public string Level4GridDesc
        {
            get
            {
                return this._level_4_grid_desc;
            }
            set
            {
                this._level_4_grid_desc = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("cells_per_object")]
        public System.Nullable<int> CellsPerObject
        {
            get
            {
                return this._cells_per_object;
            }
            set
            {
                this._cells_per_object = value;
            }
        }
    }
}
