//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SqlServer.CatalogStore
{
    using System;
    using System.Data.SqlClient;
    using Microsoft.Data.Sqlite;
    using Microsoft.EntityFrameworkCore;
    
    
    [System.ComponentModel.DataAnnotations.Schema.TableAttribute("sys_security_predicates")]
    public partial class SysSecurityPredicateCatalog
    {
        
        private System.Nullable<int> _object_id;
        
        private System.Nullable<int> _security_predicate_id;
        
        private System.Nullable<int> _target_object_id;
        
        private string _predicate_definition;
        
        private System.Nullable<int> _predicate_type;
        
        private string _predicate_type_desc;
        
        private System.Nullable<int> _operation;
        
        private string _operation_desc;
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("object_id")]
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public System.Nullable<int> ObjectId
        {
            get
            {
                return this._object_id;
            }
            set
            {
                this._object_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("security_predicate_id")]
        public System.Nullable<int> SecurityPredicateId
        {
            get
            {
                return this._security_predicate_id;
            }
            set
            {
                this._security_predicate_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("target_object_id")]
        public System.Nullable<int> TargetObjectId
        {
            get
            {
                return this._target_object_id;
            }
            set
            {
                this._target_object_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("predicate_definition")]
        public string PredicateDefinition
        {
            get
            {
                return this._predicate_definition;
            }
            set
            {
                this._predicate_definition = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("predicate_type")]
        public System.Nullable<int> PredicateType
        {
            get
            {
                return this._predicate_type;
            }
            set
            {
                this._predicate_type = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("predicate_type_desc")]
        public string PredicateTypeDesc
        {
            get
            {
                return this._predicate_type_desc;
            }
            set
            {
                this._predicate_type_desc = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("operation")]
        public System.Nullable<int> Operation
        {
            get
            {
                return this._operation;
            }
            set
            {
                this._operation = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("operation_desc")]
        public string OperationDesc
        {
            get
            {
                return this._operation_desc;
            }
            set
            {
                this._operation_desc = value;
            }
        }
    }
}
