//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SqlServer.CatalogStore
{
    using System;
    using System.Data.SqlClient;
    using Microsoft.Data.Sqlite;
    using Microsoft.EntityFrameworkCore;
    
    
    [System.ComponentModel.DataAnnotations.Schema.TableAttribute("sys_symmetric_keys")]
    public partial class SysSymmetricKeyCatalog
    {
        
        private string _name;
        
        private System.Nullable<int> _principal_id;
        
        private System.Nullable<int> _symmetric_key_id;
        
        private System.Nullable<int> _key_length;
        
        private string _key_algorithm;
        
        private string _algorithm_desc;
        
        private System.Nullable<System.DateTime> _create_date;
        
        private System.Nullable<System.DateTime> _modify_date;
        
        private System.Nullable<System.Guid> _key_guid;
        
        private object _key_thumbprint;
        
        private string _provider_type;
        
        private System.Nullable<System.Guid> _cryptographic_provider_guid;
        
        private object _cryptographic_provider_algid;
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("name")]
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("principal_id")]
        public System.Nullable<int> PrincipalId
        {
            get
            {
                return this._principal_id;
            }
            set
            {
                this._principal_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("symmetric_key_id")]
        public System.Nullable<int> SymmetricKeyId
        {
            get
            {
                return this._symmetric_key_id;
            }
            set
            {
                this._symmetric_key_id = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("key_length")]
        public System.Nullable<int> KeyLength
        {
            get
            {
                return this._key_length;
            }
            set
            {
                this._key_length = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("key_algorithm")]
        public string KeyAlgorithm
        {
            get
            {
                return this._key_algorithm;
            }
            set
            {
                this._key_algorithm = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("algorithm_desc")]
        public string AlgorithmDesc
        {
            get
            {
                return this._algorithm_desc;
            }
            set
            {
                this._algorithm_desc = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("create_date")]
        public System.Nullable<System.DateTime> CreateDate
        {
            get
            {
                return this._create_date;
            }
            set
            {
                this._create_date = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("modify_date")]
        public System.Nullable<System.DateTime> ModifyDate
        {
            get
            {
                return this._modify_date;
            }
            set
            {
                this._modify_date = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("key_guid")]
        public System.Nullable<System.Guid> KeyGuid
        {
            get
            {
                return this._key_guid;
            }
            set
            {
                this._key_guid = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.NotMappedAttribute()]
        public object KeyThumbprint
        {
            get
            {
                return this._key_thumbprint;
            }
            set
            {
                this._key_thumbprint = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("provider_type")]
        public string ProviderType
        {
            get
            {
                return this._provider_type;
            }
            set
            {
                this._provider_type = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.ColumnAttribute("cryptographic_provider_guid")]
        public System.Nullable<System.Guid> CryptographicProviderGuid
        {
            get
            {
                return this._cryptographic_provider_guid;
            }
            set
            {
                this._cryptographic_provider_guid = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.Schema.NotMappedAttribute()]
        public object CryptographicProviderAlgid
        {
            get
            {
                return this._cryptographic_provider_algid;
            }
            set
            {
                this._cryptographic_provider_algid = value;
            }
        }
    }
}
